### ISSUE TITLE
Allow users to log in with custom field

### ISSUE THREAD

**Issue by KasperJacobsen** [mattupstate/flask-security#124]
It'd be cool for user to be able to log in with another field, for example a handle field or in my case a name field.

**Comment by stamaimer** [comment]
Hi, @mattupstate. After read the `get_user` method of `SQLAlchemyUserDatastore`. I found `get_user` try to use `_is_numeric` transform `identifier`(the value of email key in login form) to integer. If the identifier can transform to a integer, it will use as the primary key to get user from user table. I don't know why do this before `get_identity_attributes`. I found this will cause bug if someone want to use phone as the user identity.
