### ISSUE TITLE
Accessing CSRF token without web page

### ISSUE THREAD

**Issue by dedalusj** [mattupstate/flask-security#156]
I'm using Flask-Security for a REST backend app that I access through AngularJS $http methods and a mobile app.

In order to retrieve the `auth_token`, I perform an HTTP POST with the authentication details as JSON data against the authentication endpoint. This result in a `CSRF token missing` response as expected.

How can I retrieve the CSRF token for subsequent requests without accessing the login page/template?

Sending a GET request to the login endpoint with the content type set to `application/json` generates an error on line 45 of views.py. This is due to the fact that Flask-WTF checks if a form `is_submitted` before validating it (`validate_on_submit` method). During a GET request, `is_submitted` is false which results in the form never being validated. If the form is never being validated, its user attribute is never set which trigger the error described above.

**Comment by rlam3** [comment]
@dedalusj were you able to find a work around for this? I'm also hitting this error because I'm trying to do a POST to get an authentication token back from my app.  Btw I'm using Flask-JWT and Flask-Marshmallow. Thanks! I appreciate it :)

**Comment by ibbad** [comment]
Hi, I am also facing the same error. I am calling using Flask for RestAPI backend and making rest calls from my java code. I need to know if I can retrieve csrf token to be added with my request from client side. Thanks for help

**Comment by karlloic** [comment]
@mattupstate Is there still no solution for this? What do you suggest as an alternative?
