### ISSUE TITLE
Consider Flask-Babel integration

### ISSUE THREAD

**Issue by mattupstate** [mattupstate/flask-security#18]
i10n and i18n could be necessary for things such as Flash messages.

**Comment by yoursdearboy** [comment]
In addition to Chris solution - to localize login message `SECURITY_MSG_LOGIN` it's also necessary to provide localize callback for login manager.

```python
security = Security(app, user_datastore)
security.login_manager.localize_callback = lazy_gettext
```

**Comment by jirikuncar** [comment]
@yoursdearboy the Flask-BabelEx has been integrated in #617 (originally from https://github.com/inveniosoftware/flask-security-fork/pull/33). Please check if it works for you and in case you have a problem open new issue. Thank you!
