### ISSUE TITLE
Can I use it without Roles?

### ISSUE THREAD

**Issue by nickretallack** [mattupstate/flask-security#188]
It appears that I can't create a SQLAlchemyUserDatastore without passing it a Role table.  What if I don't want to have a Role table?  What if I have no purpose for roles in my application?

**Comment by alexluke** [comment]
As a workaround (for SQLAlchemy at least), you can add a dummy `roles` hybrid property to the User model, and then pass `None` for the second parameter of `SQLAlchemyUserDatastore`. The other ORMs probably offer something similar.

```python
class User(UserMixin):
  # ...

  @hybrid_property
  def roles(self):
    return []

  @roles.setter
  def roles(self, role):
    pass

user_datastore = SQLAlchemyUserDatastore(db, User, None)
security = Security(app, user_datastore)
```
