### ISSUE TITLE
Document send_mail_task

### ISSUE THREAD

**Issue by nickretallack** [mattupstate/flask-security#194]
I was hoping to make my app faster at sending confirmation emails when I noticed [this](https://github.com/mattupstate/flask-security/blob/develop/flask_security/utils.py#L253) in the code.  Could you add a bit of explanation as to how to use this?  I assume it has something to do with [celery](http://flask.pocoo.org/docs/patterns/celery/).

**Comment by erwagasore** [comment]
```
from app.factory import create_celery_app, mail, security

celery = create_celery_app()

@celery.task()
def send_security_mail(msg):
    mail.send(msg)

@security.send_mail_task
def delay_security_mail(msg):
    send_security_mail.delay(msg)
```

@mattupstate, based on the code above I am getting a ```RuntimeError: maximum recursion depth exceeded``` when I run celery ```celery worker -A app.tasks -l INFO```

**Comment by joaobarbosa** [comment]
@erwagasore did you managed to fix it? I'm having the same issue :cry:

**Comment by eriktaubeneck** [comment]
I think this is likely the same issue [described in issue 340](https://github.com/mattupstate/flask-security/issues/340).

**Comment by joaobarbosa** [comment]
Thanks @eriktaubeneck!

**Comment by jxltom** [comment]
@erwagasore @joaobarbosa @eriktaubeneck 

If you are going to use factory method, recursion error will raise if it is not used properly. Here is the example based on author's example for your reference. The trick is using the ```state``` object returned by ```init_app``` for setting cutomized mail sending function. The author has explained it [here](https://github.com/mattupstate/flask-security/issues/141#issuecomment-21728482)  and [here](https://github.com/mattupstate/flask-security/issues/141#issuecomment-21744531) in #141.

```python
from celery import Celery
from flask import Flask
from flask_security import Security, .. datastore stuff ..
from flask_mail import Mail

celery = Celery()
mail = Mail()
security = Security()

def create_app():
    app = Flask(__name__)
    mail.init_app(app)
    security_ctx = security.init_app(app,..datastore stuff..)

    @celery.task
    def send_flask_mail(msg):
        mail.send(msg)

    # Flexible way for define custom mail sending function.
    @security_ctx.send_mail_task
    def delay_flask_security_mail(msg):
        send_flask_mail.delay(msg)

    # You can also define like this as shortcurt
    security_ctx.send_mail_task(send_flask_mail.delay)

    return app
```

**Comment by jirikuncar** [comment]
@jxltom we are using similar solution as you have presented in https://github.com/mattupstate/flask-security/issues/194#issuecomment-278554575. Would you mind extending the documentation with your example?

**Comment by jxltom** [comment]
@jirikuncar Sure, will do that.
