### ISSUE TITLE
Testing login and authentication

### ISSUE THREAD

**Issue by frnsys** [mattupstate/flask-security#216]
I have a route which requires authentication (`/user`). I'm trying to write a unittest but I'm having a hard time wrapping my head around how it should be written.

Here's what I have so far:

```
# within a test request context
user = User(active=True)
db.session.add(user)
db.session.commit()
login_user(user)

# current_user here is the user

# current_user within this request is an anonymous user
r = test_client.get('/user')
```

I know this has to do with my not fully understanding how these request contexts work in Flask, so any clarification would be very helpful!

**Comment by osya** [comment]
So, am I right that when using Factory Boy with Flask-Security UserFactory will now use user_datastore from Flask-Security?
