### ISSUE TITLE
SECURITY_CONFIRMABLE controls 2 different behavoirs

### ISSUE THREAD

**Issue by hoprocker** [mattupstate/flask-security#224]
In the documentation, the SECURITY_CONFIRMABLE flag is described as controlling whether a user gets confirmation email during the registration process. However, in practice it seems that this _also_ controls whether the "confirm password" field is displayed on the registration page.

To replicate:
- set `SECURITY_CONFIRMABLE = False`
- look at register page, 'Retype password' field exists
- set `SECURITY_CONFIRMABLE = True`
- on registration page 'Retype password' field is missing

I'll work on tracking this down later, for now I just want to register it.

**Comment by macfire** [comment]
+1 to allow password-retype field on with SECURITY_CONFIRMABLE = True.
The password-retype confirms that intended password is typed correctly.
Email confirmation is a separate test.

**Comment by Oliv4945** [comment]
I second that. Retype password prevents mistakes and finally improve user experience : they might think that the application is buggy and not try to ask for another password.
Although, to respect backward compatibility, it can be an option.
