### ISSUE TITLE
How to override a method of flask-security (register_user)?

### ISSUE THREAD

**Issue by DerekDomino** [mattupstate/flask-security#236]
Hello,

I'm trying without success to override a behavior of Flask-Security: sending confirmation emails. I would like them to be sent to a default e-mail address, whatever the candidate user submitted. So that the administrator can review and filter who's registering.

It seems the confirmation email is sent by `flask.ext.security.registerable.register_user()`

``` python
def new_register_user(**kwargs):
    # Define a method with new behavior
    ...

import sys

# Override registerable module method
import flask.ext.security.registerable
sys.modules['flask.ext.security.registerable'].register_user = new_register_user
sys.modules['flask.ext.security'].registerable.register_user = new_register_user

# When printing sys.modules, it seems that registerable module
# appears also there:
import flask_security
sys.modules['flask_security.registerable'].register_user = new_register_user
sys.modules['flask_security'].registerable.register_user = new_register_user
```

Unfortunately, it does not work. The original method is still used. Do you have any hints?

**Comment by Trii** [comment]
It isn't very documented but you can also attach your own callback to the `send_mail_task` function on the `flask_security.core.Security` object and it will execute instead of the flask_mail version

```python
security = Security(app, user_datastore)
security.send_mail_task(my_send_email)
```

**Comment by herman5** [comment]
Thank you for posting the override functionality! Was just what I needed! Would be great to have this in the docs

**Comment by andreibancioiu** [comment]
The feature mentioned by @Trii is documented here: https://flask-security.readthedocs.io/en/latest/customizing.html#emails.
