### ISSUE TITLE
Configuration should be 'secure by default'

### ISSUE THREAD

**Issue by adamlwgriffiths** [mattupstate/flask-security#244]
All security libs should be secure by default.
Flask-security is not.
This prevents flask-security from being run 'off the shelf'.

`SECURITY_PASSWORD_HASH` is plaintext by default. This should default to perhaps bcrypt.
`SECURITY_PASSWORD_SALT` is None by default. This should be set to a valid default. Although that would mean a common salt between any vanilla installs, any salt is better than None.

**Comment by adamlwgriffiths** [comment]
Good to see that `flask-security` still defaults to 'plaintext' password hashing.
Oh what an age we live in.

**Comment by PierreRochard** [comment]
@adamlwgriffiths Your hearts in the right place and I agree with you, but necro-posting like this is not constructive. I highly encourage you to submit a pull request that takes into account the feedback provided in this thread 1.5 years ago.
