### ISSUE TITLE
Pure JSON API

### ISSUE THREAD

**Issue by jquacinella** [mattupstate/flask-security#250]
Is there a way to have Flask Security respond only to JSON requests and not return any HTML forms? In some sense, can it be configured to not respond to GET requests but only POST requests? Not sure if this makes sense, but I am primarily using a single page app (in angular) and all I need it to do is respond to JSON and not provide an HTML interface.

(BTW, thanks again for all these modules!)

**Comment by tomazberisa** [comment]
+1
I also think this would be a great addition.

**Comment by jtmorrisbytes** [comment]
It would be great if an extension like yours could cater to both HTML and JSON endpoints. It would save people time from having to redo the same work all over again
