### ISSUE TITLE
Mail socket error can be hidden causing confusion

### ISSUE THREAD

**Issue by deadbeef404** [mattupstate/flask-security#292]
When using the forgotten password functionality, I configured my mail server to use a local postfix, but I didn't have it installed (yes, that was dumb). The problem was though, when it returned a socket connection error from within the smtplib code (effectively called from [send_reset_password_instructions here](https://github.com/mattupstate/flask-security/blob/76cf3eaf6a2f55ff74e5cc227cb06ca33ca6d593/flask_security/views.py#L247)), the flask-security code didn't handle it, so it bubbled all the way up to flask's wsgi code. 
This code then nicely ignores that error thinking the HTTP request has been terminated, and returns no data to the browser and continues happily along. This would be very confusing to users who are less experienced than myself.
I ending up patching the forgot_password function so I could display an appropriate error message and logged it using an error handler

Is this something you'd consider worth fixing in the codebase?

**Comment by mattupstate** [comment]
I believe the best approach would be to handle the exception on the app level yourself rather than bake error handling into Flask-Security. For example:

```python
@app.errorhandler(SomeError)
def on_some_error(e):
    if request.endpoint.startswith('security.'):
       return 'some custom response'
```
