### ISSUE TITLE
Allow manual authentication

### ISSUE THREAD

**Issue by leaanthony** [mattupstate/flask-security#30]
Hi, I'm currently using the stable version and am finding it really hard to be able to authenticate users manually. The main reason for requiring this is to get authentication working via an ajax call. I've noticed in the dev branch there is a utility function that looks like it might do this. Is this my only option?

Cheers.

**Comment by mandarvaze** [comment]
@melpomene 
Setting `WTF_CSRF_ENABLED=False` in your application's configuration gets rid of `CSRF Token missing` error.

**Comment by bschumacher** [comment]
@mandarvaze @melpomene 

Disabling CSRF isn't really a good idea. You can get the current token value like this:

from flask import jsonify
from flask.ext.security import LoginForm

@app.route('/login_csrf')
def login_csrf():
    form = LoginForm()
    return jsonify({'csrf_token': form.csrf_token.current_token})

You can then use the CSRF token that is returned as JSON in your login attempt, simply pass it as csrf_token with your email and password.

**Comment by radusuciu** [comment]
@bschumacher Did you attempt your suggested solution?

`requests.post(url + '/login', 
    data=json.dumps({ 
        'email': email, 
        'password': password,
        'csrf_token': requests.get(url + '/login_csrf').json()['csrf_token'] 
    }),
    headers={'content-type':'application/json'}
).json()`

Response:

`{'meta': {'code': 400}, 'response': {'errors': {'csrf_token': ['CSRF token missing']}}}`

**Comment by radusuciu** [comment]
If like me you are not married to getting that auth token then you may follow this route using cookies instead:

```python
csrf_req = requests.get(url + '/login_csrf')
csrf_token = csrf_req.json()['csrf_token']

login_req = requests.post(url + '/login',
    data={ 
        'email': email, 
        'password': password,
        'csrf_token': csrf_token
    },
    cookies=csrf_req.cookies,
    allow_redirects=False
)
```

Finally, you can then do:

```python
cookies = login_req.cookies
requests.get(url, cookies=cookies)
```

You may use the cookies for further requests. If you don't want to setup that `/login_csrf` route you can use `BeautifulSoup` too:

```python
csrf_req = requests.get(url + '/login', allow_redirects=False)
csrf_token = BeautifulSoup(csrf_req.text).find('input', id='csrf_token')['value']
```

and then proceed as above.

**Comment by spitzbubchen** [comment]
@radusuciu Any ideas on how to logout and destroy your token cookie?

**Comment by radusuciu** [comment]
@spitzbubchen This wasn't a concern for my usage, but the first thing I'd try is just posting against `/logout`.  Is that too naive?

**Comment by bschumacher** [comment]
@radusuciu I was using that for some time, recently I have switched to Flask-JWT for my API token auth stuff.

@spitzbubchen As @radusuciu suggested posting to /logout will work fine.

Alternatively, you could call the logout_user in your application logic at some point.

from flask_security import logout_user

**Comment by spitzbubchen** [comment]
@radusuciu

Doesn't seem to work. 
```
logout_req = requests.post(
        url + '/logout',
        allow_redirects = False,
        cookies = cookies
)
```
and right after that I run,
```
r = requests.get(
        url + '/api/tests',
        cookies = cookies
)
```
yet I still get secure server access without having to re-login...
