### ISSUE TITLE
Custom email template paths

### ISSUE THREAD

**Issue by patrickyan** [mattupstate/flask-security#310]
Currently, only web view templates like login, forgot password, etc can be specified in settings. Email templates should also be customizable.

**Comment by jonafato** [comment]
@patrickyan Is the problem here that you have multiple applications pointing to the same template directory, and you'd like to be able to override the location of the Flask-Security email templates to use different sets for each user type?

**Comment by patrickyan** [comment]
yes

**Comment by jonafato** [comment]
This seems like a bit of an edge case to me. You're correct that there's a difference in configurability between view templates and email templates. These should probably match, but I'm not sure that additional configuration is the best path forward.

Splitting your templates into common, users, and employees groups might be a more flexible solution given current capabilities. If you require that multiple applications share a single template directory, perhaps a [`mail_context_processor`](https://pythonhosted.org/Flask-Security/customizing.html#emails) providing content / a variable for use in choosing which content to render would work as a stopgap solution? (Admittedly, this is a hack, but I lean toward the "separate template directories" approach long-term.)

**Comment by patrickyan** [comment]
That sounds like a good workaround for now! Thanks
