### ISSUE TITLE
Alter roles needed for views

### ISSUE THREAD

**Issue by colinmcintosh** [mattupstate/flask-security#321]
For login and register views the default role level is @anonymous_user_required. Can this be altered to allow for adjustment of roles required for each built-in view. A example use case for this is requiring a the role "admin" in order to create a user account for another user.

**Comment by jonafato** [comment]
The [`@roles_required`](https://pythonhosted.org/Flask-Security/api.html#flask_security.decorators.roles_required) decorator provides this functionality. You can also disable user registration by setting the [`SECURITY_REGISTERABLE`](https://pythonhosted.org/Flask-Security/configuration.html#feature-flags) configuration value to `False`. I'd recommend using something like [Flask-Admin](https://flask-admin.readthedocs.org/en/v1.1.0/) or a custom view to provide admin-only user account creation.

**Comment by colinmcintosh** [comment]
Normally the @roles_required decorator would handle this but since [that view is defined in Flask-Security](https://github.com/mattupstate/flask-security/blob/develop/flask_security/views.py#L101) I can't alter the decorator. Disabling the registration page is also not the solution I'm looking for as I want to use the registration page.

What you are suggesting is that I recreate the register view and apply the correct decorator, which seems excessive for what I'm trying to do.

**Comment by jonafato** [comment]
The `register` view is meant to be a method for new users to register an account on the application. If you plan to have site administrators creating accounts on behalf of new users, I'd suggest using some of Flask-Security's functions in a custom view, instead. It's bad practice to have anyone other than an end user decide / know / transmit a password, and repurposing this view would require that to happen.
