### ISSUE TITLE
Stateless authentication

### ISSUE THREAD

**Issue by Diaoul** [mattupstate/flask-security#329]
Is it possible to use Flask-Security for a RESTful API? It seems a session is created anyway, that's not stateless.
The ability to turn off the use of session with a decorator would be great.

In my case I have two blueprints frontend + api (authenticated). So far I've not been able to come up with a good solution. I'd like to reuse the current_user and roles_required decorators as much as possible.

**Comment by mr337** [comment]
+1 with this since I too am not facing the same issue.
