### ISSUE TITLE
Allow to disable redirect on unauthorized request

### ISSUE THREAD

**Issue by alexandre** [mattupstate/flask-security#333]
Hi,

When we do a unauthorized request, the bellow function executes a redirect. This is ok, but if I'm using flask-security in  a API this makes no sense [IMHO].

__URL__: https://github.com/mattupstate/flask-security/blob/develop/flask_security/decorators.py#L46
__code__:
``` python

def _get_unauthorized_view():
    cv = utils.get_url(utils.config_value('UNAUTHORIZED_VIEW'))
    utils.do_flash(*utils.get_message('UNAUTHORIZED'))
    return redirect(cv or request.referrer or '/')
```

A idea: using a boolean variable (e.g. UNAUTHORIZED_REDIRECT) we can allow disable this redirect:
``` python
# core.py
_default_config = {
<another vars>,
 UNAUTHORIZED_REDIRECT = True
```
Using a default value True that don't breaks the current function behavior...so, the __\_get\_unauthorized_view()__ checks the new variable:

``` python

def _get_unauthorized_view():
    cv = utils.get_url(utils.config_value('UNAUTHORIZED_VIEW'))
    utils.do_flash(*utils.get_message('UNAUTHORIZED'))
    if not UNAUTHORIZED_REDIRECT:
         return 'unauthorized request', 403
    return redirect(cv or request.referrer or '/')
```

I commented about it on irc chanel, but I forgot to send this question/idea to Github. =]

**Comment by ElvisTheKing** [comment]
workaround: if login_required is used in api view and obviosly redirect is not what you want - you can use auth_token_required instead, it doesn't issue redirects (which is a bit inconsistent itself)

**Comment by wangyandong-ningxia** [comment]
+1 for the request.

**Comment by boazin** [comment]
Don't know if it is related or not (can open another thread)
Even when using `auth_token_required`
with the decorators:
```
@auth_token_required
@roles_accepted('provider', 'admin')
```

I'm getting a redirect and not a 403 when I have an access token with the incorrect role (a valid user that logged in and got a token, but has a different role)

**Comment by woshihaoren** [comment]
@boazin 
 How do you use @roles_accepted('provider', 'admin')
Can you give me some tips?

**Comment by boazin** [comment]
@woshihaoren - pretty straight forward.
https://pythonhosted.org/Flask-Security/api.html#flask_security.decorators.roles_accepted
Nothing fancy

**Comment by mgd722** [comment]
For clarity's sake it should be noted that `SECURITY_UNAUTHORIZED_VIEW` must actually be set equal to `None` to get a 403 returned; leaving it undefined will return 200 with a flashed unauthorized message.
