### ISSUE TITLE
Add slash before or after token in flask-security URLs correctly

### ISSUE THREAD

**Issue by Jaza** [mattupstate/flask-security#343]
A number of flask-security views (login, reset, confirm) currently assume that the URL does not end with a slash (i.e. it conforms to the default, such as '/login').

I prefer URLs to end with a slash, so I've configured my flask-security URLs as such (e.g. '/login/').

For URLs with a token, this results in flask-security generating links such as 'http://mysite.com/reset//token-here-h4938r3498h39thc98h498', whereas it should be 'http://mysite.com/reset/token-here-h4938r3498h39thc98h498/'.

**Comment by jonafato** [comment]
Fixed by #347
