### ISSUE TITLE
Confirm and commit user before performing login

### ISSUE THREAD

**Issue by Jaza** [mattupstate/flask-security#345]
I have my User model set up, such that when the user is saved, 'active' is set to 'True' if 'confirmed_at' is not None. This means that a newly-created user can be inactive, and that when he/she follows the 'confirm email' link, 'active' and 'confirmed_at' get set.

However, for this to work, the 'confirm_email()' callback in flask-security needs to commit the changed user model to the DB immediately (rather than 'after_this_request'), and the user needs to be logged in after confirming the email (current behaviour is to do so before confirming).

**Comment by jonafato** [comment]
@Jaza This seems redundant. The function of the confirmable feature is to prevent users who have not confirmed their email addresses from logging in. Why would you want to combine the `active` and `confirmed_at` features into a single one?

**Comment by jonafato** [comment]
Closing due to lack of response.
