### ISSUE TITLE
Check whether the user is None in _check_user() in decorator.py

### ISSUE THREAD

**Issue by ychiaoli18** [mattupstate/flask-security#353]
If you use a valid access token of an user, but this user is not in the database right now. Then the user will be None, and there will be an exception if you access it's password later.

<code>
 user = _security.login_manager.token_callback(token)
<code>

**Comment by jonafato** [comment]
@ychiaoli18 Can you provide a minimal example illustrating this bug?

**Comment by jonafato** [comment]
Closing due to lack of response.
