### ISSUE TITLE
How to login to Flask-Security from native mobile app

### ISSUE THREAD

**Issue by sureshjoshi** [mattupstate/flask-security#358]
Apologies for a cross-post (https://stackoverflow.com/questions/27925704/how-to-login-to-flask-security-from-native-mobile-app), but this is more of a question rather than a bug (so far, anyways).

I setup Flask-Security for my single-page app - and ran into the CSRFToken issue that a lot of people have had (Flask-Security CSRF token). From my web app, I put the CSRFToken in HTML, scrape the page to find it, and use it to send in my login request from Angular as a request header in my POST.

This works out well, however, what is the procedure to protect APIs if I'm accessing them via ajax from a mobile app? Because what I would assume I need to do is to first login from the mobile app, store my auth_token, and use that on subsequent API calls.

The problem here... Do I need to do a get on my /login page, scrape for CSRF token, use that to send a login request to my server, get the auth token first?? Scraping HTML for a CSRF token from mobile apps over REST seems kinda sketch.

Also, quick aside: I'm not sure if I should guard APIs as:

@login_required 
/api/v1/foo
or
@auth_token_required 
/api/v1/foo

**Comment by nfvs** [comment]
Seems like your question has been answered over at StackOverflow (this wasn't even a bug to begin with) so I think you can safely close it.

**Comment by sureshjoshi** [comment]
Good call @nfvs. And for the sake of helping Googlers:

From SO:
-------------
I am not sure flask-security has been designed to protect APIs. CSRF Token has been designed to protect your login form from automated login. If this is really what you want, you would probably better disable it (but this is probably a bad idea).

Take a look at how other have protected their APIs. To my knowledge, nobody use a password scheme to protect a mobile API. You should probably generate a unique key for each user and have your mobile app pass this key in a header to your API HTTP calls.
------------

And my comment on that answer:
------------
A week or so ago, I switched over to protecting my API with Flask-JWT and got rid of the standard forms, in favour of a SPA-based login and session handling.
------------
