### ISSUE TITLE
_pwd_context.verify_and_update - Where is this defined

### ISSUE THREAD

**Issue by flowstack** [mattupstate/flask-security#364]
I'm not sure if this is the correct place to post this. If not I am sorry. I am trying to determine where the `verify_and_update` method is defined. In utils.py this line:

```verified, new_password = _pwd_context.verify_and_update(password, user.password)```

gives my back `False, None`, and is preventing users from logging in. This only seems to happen if the user has recently reset their password. If the password has not been changed since registration login works fine.

**Comment by longhotsummer** [comment]
_pwd_context is a reference to a `CryptContext` instance from [passlib](https://pypi.python.org/pypi/passlib). It is established in [core._get_pwd_context()](https://github.com/mattupstate/flask-security/blob/develop/flask_security/core.py#L244)

**Comment by jonafato** [comment]
@flowstack The docs for this function are location [here](https://pythonhosted.org//passlib/lib/passlib.context.html#passlib.context.CryptContext.verify_and_update). Are you still able to produce this issue? If so, can you provide a minimal working example that illustrates the problem?

**Comment by flowstack** [comment]
Thanks. I've manage to sort it. I think I had to do a bit of a workaround but can't remember. I'll dig out the code when I get home

**Comment by jonafato** [comment]
@flowstack I'm going to close this for now. If you're able to reproduce the issue you saw, feel free to reopen it.
