### ISSUE TITLE
Adding CORS headers??

### ISSUE THREAD

**Issue by bnmnetp** [mattupstate/flask-security#385]
Hi,

After a successful login I would like to add the following access control header to the response.

```
response.headers.add('Access-Control-Allow-Credentials', 'true')
```

I can see how to customize the login template, and I can see that I can configure a POST_LOGIN view or URL.  But is there a way to add this header without making a custom version of flask-security?

Thanks,

Brad

**Comment by jonafato** [comment]
@bnmnetp Consider using [Flask-CORS](https://flask-cors.readthedocs.org/en/latest/) for this purpose. Note that this header needs to be sent with each response. The Mozilla Developer Network has [good documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS?redirectlocale=en-US&redirectslug=HTTP_access_control#Access-Control-Allow-Credentials) on this.

**Comment by bnmnetp** [comment]
That looks just like what I want.  Thanks.  Obviously my googling skills failed on that one.

**Comment by bnmnetp** [comment]
I've just spent the day being thoroughly unsuccessful with the flask-cors extension.  Maybe I'm just going at it wrong but I cannot get it to work with even a very simple request if that request is in my own blueprint. 

I have been successful using an @after_request decorator, but I would really like finer control over which request.

The ``after_this_request`` call in the login view seems like a perfect place to inject what I want.   

Would there be any interest in adding a configurable POST_LOGIN_CALLBACK that could be called in addition to the current ``_commit`` ?

**Comment by mattupstate** [comment]
I'm sorry to say this, but CORS headers will never be handled by Flask-Security. Have you reached out for help with Flask-CORS yet?

**Comment by bnmnetp** [comment]
Yes, I have.  So maybe they will have some help for me.

I'm curious though, why you say that CORS headers will never be handled by Flask-Security.  I can understand why you might not want to get involved with a lot of the cross site origin stuff on every request, but allowing authentication headers to be set post login seems like a pretty valid use case for you to support.

**Comment by mattupstate** [comment]
The reason is that there are libraries that take care of this already and are very good at it. Flask-Security, as far as I understand my own code, does not get in the way of Flask-CORS or any code you might write yourself to manage CORS headers. If you can prove that Flask-Security is preventing Flask-CORS or your own code from properly setting CORS headers then we can address that issue. Otherwise I can't justify adding the complexity to the project.

**Comment by bnmnetp** [comment]
Thanks for the explanation.

As I said, I **can** make it work with my own code.  So I'll press on, and hope that I'll figure out where I'm going wrong with Flask-CORS so my solution doesn't feel like such a hack.

**Comment by jonafato** [comment]
@bnmnetp does the [resource specific CORS](https://flask-cors.readthedocs.org/en/latest/#resource-specific-cors) example not solve your issue? If not, it's probably not working as intended and should be fixed.

**Comment by bnmnetp** [comment]
@jonafato Thanks, I've tried both ways.

As you can see from the log I get strangely conflicting messages.  Which makes me think that flask-CORS might be broken.  But, I'm new to both Flask-Security and Flask-CORS.

```
DEBUG:flask.ext.cors:Enabling <function home at 0x1039e2b70> for cross_origin using options:{'supports_credentials': True}
DEBUG:runestone.cors:Request to '/login' matches CORS resource '/login'. Using options: {'origins': ['.*'], 'supports_credentials': True, 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'intercept_exceptions': True, 'automatic_options': True, 'send_wildcard': False, 'vary_header': True, 'allow_headers': ['.*'], 'resources': {'/api/*': {'origins': '*'}, '/login': {'supports_credentials': True}}}
DEBUG:runestone.cors:'Origin' header was not set, which means CORS was not requested, skipping
DEBUG:runestone.cors:Settings CORS headers: MultiDict([])
```

**Comment by bnmnetp** [comment]
Well, just for the record, it was my own stupidity.  The CORS spec says that you shouldn't respond with any CORS headers unless the request has an Origin header.  My quick little test did not follow the rules, so everything works as expected now.

Thanks for making Flask-Security!

Brad
