### ISSUE TITLE
override fields of the registration form

### ISSUE THREAD

**Issue by ruNickStone** [mattupstate/flask-security#386]
How do I override the default registration form in Flask-Security is to remove all label attributes.
In the documentation there is a section of the customizing view, but in the example is to add the fields to the form, and I need to change the default.

Sorry for my English, not main language

**Comment by jonafato** [comment]
You want to remove rather than change the labels for the registration form? Why not just override the template and render the form without them?

**Comment by diegoponciano** [comment]
In the same docs there is a section dedicated to forms.  
Look for ```register_form```, and create your own form.  
https://pythonhosted.org/Flask-Security/customizing.html#forms
