### ISSUE TITLE
Change email

### ISSUE THREAD

**Issue by Bekt** [mattupstate/flask-security#392]
I am not sure if this is a flask-login question or flask-security. 

How should one go about changing the email field for an existing user? Since the field is unique, I wonder if it will have side-affects when dealing with email changes.

**Comment by joostdevries** [comment]
We have a custom process for email changes (with verification) but you should just be able to update the field without side-effects.

**Comment by jonafato** [comment]
This is a possible duplicate of #283. Flask-Security does not currently have a way to change a user's email address with the confirmable logic, so a custom solution would be needed at this time. If you're not using `SECURITY_CONFIRMABLE`, simply changing the email address on the user object should have no unexpected consequences within Flask-Security.

**Comment by jirikuncar** [comment]
See #656.
