### ISSUE TITLE
Invalidating Auth Tokens

### ISSUE THREAD

**Issue by aphillipo** [mattupstate/flask-security#395]
Hi Flask Security!

If a new login happens I want to make certain that old auth tokens (for that user) no longer work.

Is this easy or possible?  

Thanks,

Andy.

**Comment by jonafato** [comment]
Can you elaborate a bit on what you mean by "auth tokens" here? Are you asking for the ability to have a new login session invalidate all other login sessions?

**Comment by aphillipo** [comment]
I guess I should just log out a user when they login?  Would that work?

**Comment by jonafato** [comment]
What's your goal here? Logging out a user when they log in would simply result in the inability to stay logged in.

**Comment by aphillipo** [comment]
So, firstly I'm using @auth_token_required decorator for an API. 

I just did a little test to see if two different auth tokens would allow access even when a new login happens and it does.  I was assuming that if someone else logs in and gets an auth token we could make sure older auth tokens are not valid.

This doesn't seem to be the case with flask-security... maybe I'm misunderstanding how auth tokens work?

**Comment by mattupstate** [comment]
Flask-Security does not offer a way to invalidate a token other than changing the secret key that tokens are signed with. This, however, would invalidate every token out in the wild. That said, it sounds as if you want a user to only be able to log in from one place at a time. Is this a fair assumption?

**Comment by aphillipo** [comment]
Yes, I just want to be able to make certain that any tokens issued can be invalidated, I do understand that they are also time based which is good that they will not work after a certain time.  I do not want a stolen token to be reused for say X days while another user is logged in and using a previously issued token.

Ideally I'd like to be able to request a new token every hour (or less) transparently and invalidate all current tokens.  Any logins that are using the old token could then receive a special error saying "You have been logged out because you have logged in somewhere else.".  This would alert the user to any theft of their authentication.

Is the IP Address checked in token auth as well?

**Comment by jonafato** [comment]
I misunderstood here at first. If you're trying to invalidate old logins when a new one happens, your best bet is probably to use server side sessions and keep track of something like `(user_id, login_ip)`. This way, you can invalidate (remove) any sessions belonging to a particular user that don't match the new login ip.

**Comment by aphillipo** [comment]
I've built a single page webapp and I think authenticating an API with localStorage and headers is very nice and clean.  My concern is in the case of stolen auth tokens we should at least tell the user they have been taken?

**Comment by mattupstate** [comment]
Flask-Security is not the tool for you then. I would suggest Flask-JWT instead.

**Comment by aphillipo** [comment]
Yes, I've seen some info on that.  Does look great and I know you wrote it.  I just has flask security all set up and thought I could 'get away with it' for now.  It would have been good enough if I could invalidate issued tokens - actually I can just store issued auth tokens and user_id in the DB and remove them when a new one is issued.  

This actually makes a lot of sense to me?  I'm still not sure how to use JWT...

**Comment by aphillipo** [comment]
Okay you can close this - I'll have a stab at using Flask-JWT as soon as I can.

**Comment by aphillipo** [comment]
Doesn't look like you can invalidate tokens issued with flask-jwt either: https://github.com/mattupstate/flask-jwt/issues/45

**Comment by mattupstate** [comment]
I didn't say you could invalidate tokens, just that Flask-JWT _might_ be more appropriate for your needs. I would say that your requirement of only allowing one token for one user to be valid at any given point in time is quite uncommon. And regardless of if you have a SPA or traditional web app, it would require some sort of unique data about the client to be persisted across requests that you can refer to and manipulate at your own will. This goes against what I would loosely refer to as the "access token pattern", which is a mechanism for authentication against stateless services. Otherwise, most applications allow a user to be "logged in" or use multiple tokens without concern.
