### ISSUE TITLE
flask-security login via username and not email

### ISSUE THREAD

**Issue by boazin** [mattupstate/flask-security#396]
I wanted to have the field in User model that through it the user logs in as username instead of email

I defined:
```
app.config['SECURITY_USER_IDENTITY_ATTRIBUTES'] = 'username'
```

But I'm still getting:

```
user_datastore.add_role_to_user(name, 'mgmt')
      File "/Users/boazin/sentinal/sentinel-cloud/.env/lib/python2.7/site-packages/flask_security/datastore.py", line 105, in add_role_to_user
        user, role = self._prepare_role_modify_args(user, role)
      File "/Users/boazin/sentinal/sentinel-cloud/.env/lib/python2.7/site-packages/flask_security/datastore.py", line 72, in _prepare_role_modify_args
        user = self.find_user(email=user)
      File "/Users/boazin/sentinal/sentinel-cloud/.env/lib/python2.7/site-packages/flask_security/datastore.py", line 203, in find_user
        return self.user_model.query.filter_by(**kwargs).first()
      File "/Users/boazin/sentinal/sentinel-cloud/.env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 1333, in filter_by
        for key, value in kwargs.items()]
      File "/Users/boazin/sentinal/sentinel-cloud/.env/lib/python2.7/site-packages/sqlalchemy/orm/base.py", line 383, in _entity_descriptor
        (description, key)
    InvalidRequestError: Entity '<class 'flask_app.models.User'>' has no property 'email'
```
It seems that email is hardcoded into flask-security...

Can I change it?

**Comment by mattupstate** [comment]
Apparently you're user model doesn't have an email property at all, which is something that was not accounted for. This is indeed troublesome for the datastore, as it doesn't account for lookups using anything other than `id` or `email`.

**Comment by boazin** [comment]
So if I dont want email but a uaername I must have a username@dummy.com?

**Comment by mattupstate** [comment]
There might be a workaround for now. How is `add_role_to_user` being invoked? Are you using the builtin management command or did you import the function into your application code somewhere?

**Comment by boazin** [comment]
It's in my application code (I'm creating a user and then attaching the
correct role to it)

**Comment by mattupstate** [comment]
Are you passing the username or the user object to the function as the first argument?

**Comment by boazin** [comment]
yes - user_datastore.add_role_to_user(name, 'mgmt')

**Comment by mattupstate** [comment]
Try passing a user object instead of the username, it should support that parameter type.

**Comment by boazin** [comment]
nice try...

I'm getting a different error now:

ProgrammingError: (psycopg2.ProgrammingError) column user.email does not exist


I'm guessing this is embedded hard into the code.


Never mind - I'll use the workaround

**Comment by boazin** [comment]
By the way - your solution did work... forgot to upgrade the DB :|
Thanks...

**Comment by aquatic7** [comment]
Sorry for reviving, but what was your workaround @boazin   ?
