### ISSUE TITLE
'next' arg is not passed if using @roles_required() or @roles_accepted()

### ISSUE THREAD

**Issue by lstep** [mattupstate/flask-security#4]
When protecting a resource with either @roles_required() or @roles_accepted(), after a successful login, the next arg is not passed (url is http://localhost:5000/login )
When protecting a resource with @login_required(), "next" is correctly passed in the url: http://localhost:5000/login?next=%2Fmypage

That means tha when the login is successful, the user is always redirected to the '/' resource.

**Comment by woshihaoren** [comment]
@lstep 
Hi,Can you give me some tips about roles_required or roles_accepted,
When I use it, It can't work
