### ISSUE TITLE
How to customize password validation?

### ISSUE THREAD

**Issue by macfire** [mattupstate/flask-security#415]
I would like to change the required length and regex validation for the password field. (Ex. typical require min 8 length, at least 1 Capital, 1 lowercase, 1 special character)

Is it possible to override the current settings without modifying the source code?

I've reviewed issue #130 and 78903fa2e50d0d54085b79ab3696a1b7e921b1f6, but the answer is not clear to me. Thanks.

**Comment by pwgn** [comment]
+1

Is it possible to at least set the min length requirement?

Thank you guys!

**Comment by ekw** [comment]
You could define your own validators and use them instead when you define your forms.  See https://github.com/mattupstate/flask-security/blob/develop/flask_security/forms.py#L70 and how they're later used in forms.

**Comment by macfire** [comment]
@ekw, thanks.

Example:
```python
from flask_security.forms import RegisterForm, PasswordField, Required, Length

password_required = Required(message='PASSWORD_NOT_PROVIDED')
password_length = Length(min=8, max=128, message='PASSWORD_INVALID_LENGTH')

# Extend Forms
class ExtendedRegisterForm(RegisterForm):

    password = PasswordField('Password', validators=[password_required, password_length])
```

**Comment by acnebs** [comment]
This doesn't address the difficulty in then adding this form to your register view, as I don't know of a way to do it.

You need to pass ExtendedRegisterForm as the user_register_form to the template, but that is not accessible, so really you need to create your own register view, but then you have two register views, one of which is "unsecured".
