### ISSUE TITLE
is_authenticated() etc. methods break with Flask-Login 0.3.0

### ISSUE THREAD

**Issue by boydgreenfield** [mattupstate/flask-security#416]
Which changes them to properties and causes them to raise `TypeError`s all over the place. 

Relevant Flask-Login changelog: https://github.com/maxcountryman/flask-login/blob/5415c146df9dd560cc9475227c34866851532e9e/test_login.py

**Comment by boydgreenfield** [comment]
@mattupstate – happy to draft a PR here, but I think a design decision needs to be answered first: 

* Specifically, do you want to have this coincide with a point release update that also requires `Flask-Login>=0.3.0`, or whether you want to instead handle both the case where `is_anonymous` is a property _and_ a method?

**Comment by mattupstate** [comment]
I would simply change the source to use the property and release with a new Flask-Login dependency spec.

**Comment by ialex** [comment]
I made a PR based on the conversation let me know if we need to change something else to merge it.

https://github.com/mattupstate/flask-security/pull/417

**Comment by vmalloc** [comment]
+1 for creating a point release anchoring this change

**Comment by boydgreenfield** [comment]
Oh thanks @ialex – sorry I didn't get back to checking in on this until now. And appreciate the patch!

**Comment by ialex** [comment]
great, would be nice to merge the PR. cc @mattupstate

**Comment by dreucifer** [comment]
You could probably keep backwards compatibility by checking to see if is_authenticated is callable first, then returning the appropriate value based on that.

**Comment by jonafato** [comment]
@dreucifer please see #393, which already does this check and will be compatible across versions. I like this solution for the moment because it allows users / developers to upgrade Flask Security without imposing other changes on them.

**Comment by ialex** [comment]
I think its nice to keep backward compatibility. +1 #393

**Comment by drsounds** [comment]
I have this problem too.

**Comment by vmalloc** [comment]
I hate it when projects do that, messing with properties and predicates. Now whenever someone changes their code to reflect that but forget to bump the dependency, they have a security breach because they're checking the truthfulness of a method...

**Comment by collinstocks** [comment]
:+1: #393

**Comment by luckenbach** [comment]
#393 +1

**Comment by mattupstate** [comment]
@jonafato I'm going to leave it to you to handle this one. I'm getting married this weekend and I'll be off in Scotland until October 5th. I'm going to try and touch my computer as little as possible, but if you prepare a release, and I have a moment, I'll publish it to pypi.

**Comment by mafrosis** [comment]
+1 backwards compat!

**Comment by citizen-stig** [comment]
Why is it a problem to break backward compatibility? And this issue shows, that better have a freezed versions of depenend packages and updates them accordingly

**Comment by citizen-stig** [comment]
Short term solution, for those, who came from google search:
```pip install Flask-Login==0.2.11```

**Comment by JohnLockwood** [comment]
Hi,

Anyone know the status of this one?  I did a quick patch but should have checked the issue first, as you guys already are miles ahead of me with the backward compatibility and the glaven!  Thanks, and not submitting a PR because it sounds like there are better ones ahead of mine.

**Comment by elvisw** [comment]
@citizen-stig I have this problem too. rollback the flask-login to 0.2.11 can solve the issue.

**Comment by velochy** [comment]
I understand the patch is ready. Is there an ETA for it to be merged?

**Comment by jonafato** [comment]
@mattupstate I was also out of town for a while, but #429 is my take on the fix. If you like the approach, let me know. If not, I'd suggest just requiring `flask-login>=0.3.0`. In either case, I'm happy to prepare a release for you to publish to PyPI.

**Comment by rochacbruno** [comment]
Will this be released to PyPI?  recent instalations from **pip install flask_security** are failing because of the lack of this patch.

**Comment by blacked** [comment]
:+1: to PyPi

**Comment by aldarund** [comment]
+1 to PyPi please, if you install flask-security from pypi right now it will not worj

**Comment by lnielsen** [comment]
Any news on when we will have a release with this fix in?

**Comment by cstrutton** [comment]
+1 for the Pypi release please and thanks for a great extension.  As always I get half way through rolling my own when I realize someone has already done all the heavy lifting for me...  thanks for all your hard work
