### ISSUE TITLE
Pin the flask-login version to 0.2.11

### ISSUE THREAD

**Issue by lu-zero** [mattupstate/flask-security#433]
flask-login 0.3 changed is_authenticated and is_anonymous to properties, apparently, Flask-Security documentation refers to them as callable.

**Comment by Atorich** [comment]
+1

**Comment by xarg** [comment]
+1

**Comment by halflings** [comment]
+1, and ideally adapt to this change (by checking the type of is_authenticated to support both versions)

**Comment by nekwebdev** [comment]
+1

**Comment by vmalloc** [comment]
+1

**Comment by KeNaCo** [comment]
+1

**Comment by CandySunPlus** [comment]
+1+1

**Comment by baocaixiong** [comment]
+1

**Comment by dannydufau** [comment]
+1

**Comment by mattupstate** [comment]
Fixed by #438
