### ISSUE TITLE
Is there a way set set the login message per request/user locale?

### ISSUE THREAD

**Issue by jgill333** [mattupstate/flask-security#440]
On a multilingual site (e.g. there are various users viewing the site using different languages at the same time) is there a way to change the login message that Flask-Security utilizes?

The default value is "Please log in to access this page."

What if you do not know the user's locale until their browser accesses a URL/page? How do you set the message for the login message (or any others) using something like Flask-Babel/gettext.

`security.something.login_manager.login_view = _('Just a test')`

**Comment by jonafato** [comment]
This is a duplicate of #18. Please follow that issue for updates, and contributions are always welcome.
