### ISSUE TITLE
ADD control anonymous_user_required decorator in RESET PASSWORD flow

### ISSUE THREAD

**Issue by eevmanu** [mattupstate/flask-security#456]
In some cases (like taking Github.com as an example) could be useful to access forgot and reset password views meanwhile you're logged in. But using this extensions the default behaviour is when you access to /reset or /reset/{token} you get a redirect to your post login view (default '/'), so a mechanism to avoid anonymous_user_required decorator here (https://github.com/mattupstate/flask-security/blob/develop/flask_security/views.py#L241) and here (https://github.com/mattupstate/flask-security/blob/develop/flask_security/views.py#L265) is needed.

**Comment by jirikuncar** [comment]
I have no strong opinion about this one. Maybe @mattupstate or @jonafato had a similar discussion in the past.
