### ISSUE TITLE
password_confirm not shown

### ISSUE THREAD

**Issue by Arti3DPlayer** [mattupstate/flask-security#459]
Why ```password_confirm``` field is not appear at register form ?

I looked at source and saw this:
```
class PasswordConfirmFormMixin():
    password_confirm = PasswordField(
        get_form_field_label('retype_password'),
        validators=[EqualTo('password', message='RETYPE_PASSWORD_MISMATCH')])

class RegisterForm(ConfirmRegisterForm, PasswordConfirmFormMixin,
                   NextFormMixin):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        if not self.next.data:
            self.next.data = request.args.get('next', '')
```

**Comment by jonafato** [comment]
Do you have [`SECURITY_CONFIRMABLE`](https://pythonhosted.org/Flask-Security/configuration.html#feature-flags) set to `True` in your application configuration by any chance? The wording here is a bit overloaded, but the `ConfirmRegisterForm` (enabled by this setting) confirms the email address and not the password. The regular `RegisterForm` is used by default (i.e. when you have `SECURITY_CONFIRMABLE = False` set), which does confirm the password.

If this is not the issue, are you using a custom registration template? The [default](https://github.com/mattupstate/flask-security/blob/e01cd63a214969cf8e4ee800d398e1c43b460c7f/flask_security/templates/security/register_user.html) one should show everything correctly, but a custom one would take precedence.

**Comment by Arti3DPlayer** [comment]
Yes, sorry for question. I forget about this option.
