### ISSUE TITLE
Using username instead of email for login

### ISSUE THREAD

**Issue by AbdealiJK** [mattupstate/flask-security#464]
I wanted to use a username instead of the email field to login . Is this possible ?

**Comment by renejahn** [comment]
In flask-security's core.py in line 91:

`'USER_IDENTITY_ATTRIBUTES': ['email']`

I guess you could just add username:

`'USER_IDENTITY_ATTRIBUTES': ['email', 'username'],`

utils.py line 365 defines a function named "get_identity_attributes", which is used by the datastore implementations to query for the user.

So the solution above should enable you to find a user by username and other attributes which are unique to the user database model.

**Comment by AbdealiJK** [comment]
That isn't a complete solution though.
The forms for login, registration, etc ask for email.
Even the login view expects email and throws an error if it isn't there in the data given to it.
I tried that out and found various errors being thrown which became difficult to fix.


-----Original Message-----

**Comment by renejahn** [comment]
Explaining how to override the default forms would not have addressed the question, in my opinion.
When using init_app you can simply drop in your own LoginForm. The you could change the label to be "username" or "username or email".

**Comment by jirikuncar** [comment]
It is possible as explained above with combination of `'USER_IDENTITY_ATTRIBUTES': ['email', 'username'],` and custom `LoginForm`.

**Comment by paway** [comment]
I think the following code would solve the problem without pass `USER_IDENTITY_ATTRIBUTES`.
phone/email both are unique. let's find the email by the phone number and pass the correct email value to "flask-security".
```class ExtendedLoginForm(LoginForm, FlaskForm):
    phone = TelField('phone', validators=[phone_required, phone_validator])

    def __init__(self, *args, **kwargs):
        super(ExtendedLoginForm, self).__init__(*args, **kwargs)
        user = User.query.filter_by(phone=self.phone.data).first()
        if user:
            self.email.data = user.email
```
after reading a lot your code. I think the email way is everywhere and solid. As there is `USER_IDENTITY_ATTRIBUTES` method, why not Give the user's freedom to choice.
