### ISSUE TITLE
SECURITY_PASSWORD_SALT when using bcrypt

### ISSUE THREAD

**Issue by genxstylez** [mattupstate/flask-security#470]
as titled, I believe bcrypt generates its own salt every time the password is generated. I think it's better to detect if bcrypt is used then there should not be a runtime error like the one below.

`RuntimeError: The configuration value `SECURITY_PASSWORD_SALT` must not be None when the value of `SECURITY_PASSWORD_HASH` is set to "bcrypt`
related: https://github.com/mattupstate/flask-security/issues/268

**Comment by DeimosA** [comment]
SECURITY_PASSWORD_SALT is used for "double salting" or "salting & peppering" (whatever you prefer). This is a common salt used in addition to the salt that bcrypt (or other algorithms) generate.

**Comment by mattupstate** [comment]
Thanks @DeimosA for explaining this.

**Comment by jplatte** [comment]
Why is this done though? A quick lookup of "double salting" turns up [this SO question](https://stackoverflow.com/q/2065558) with only one answer implying that it is basically useless.
