### ISSUE TITLE
Using change_user_password fails with AttributeError, unable to find user._get_current_object()

### ISSUE THREAD

**Issue by avilaton** [mattupstate/flask-security#473]
Hi Matt,

Trying to use `change_user_password` from `flask_security.changeable` I ran into this error:

```
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/gavila/tonTrabajo/clients/squaretrade/device-repair/device_repair/views/users.py", line 367, in post
    change_user_password(user, password_form.new_password.data)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask_security/changeable.py", line 46, in change_user_password
    user=user._get_current_object())
AttributeError: 'User' object has no attribute '_get_current_object'
```

I ended up using `encrypt_password` but I would like to use the former to get the emails/signals sent.
My user object has the `UserMixin` and the extension works for everything else. I understand this `_get_current_object()` comes from werkzeug but I'm unable to point out where I'm messing it up.

Any ideas what might be wrong?

Thanks in advance!

**Comment by avilaton** [comment]
Maybe I should add that the `user` I'm passing to the function is not the actual logged in user but another. The logged in user is the admin, and he/she would be changing another user's password in this flow.

**Comment by wewearglasses** [comment]
Same problem here. in 1.7.4 the parameter is `user=user`, but changed to `user._get_current_object() in 1.7.5`

**Comment by frnsys** [comment]
any updates on this? just ran into this issue myself.

**Comment by jirikuncar** [comment]
We can clean the API so `change_user_password` expects an instance of user instead of LocalProxy.
