### ISSUE TITLE
current_user.is_authenticated() was changed to an attribute

### ISSUE THREAD

**Issue by alexwaters** [mattupstate/flask-security#480]
just changing it to {% if current_user.is_authenticated %} in line 16 of base.html should fix it. Happy to make a pull req, lmk if I should.

**Comment by jonafato** [comment]
Flask-Security 1.7.5 switched to using properties for `is_authenticated` and `is_anonymous` for compatibility with Flask-Login >= 0.3.0. Flask-Security doesn't have a base.html. If other instances of this attribute change are found, please submit a PR. If not, we should close this issue.
