### ISSUE TITLE
Signals create verbose console statements

### ISSUE THREAD

**Issue by alexwaters** [mattupstate/flask-security#488]
Here is my code:

```
from flask.ext.security.signals import user_registered
@user_registered.connect_via(app)
    def user_registered_sighandler(app, user, confirm_token):
        default_role = user_datastore.find_role("User")
        user_datastore.add_role_to_user(user, default_role)
        user_datastore.deactivate_user(user)
        db.session.commit()
```

When a user registers, my console gets a dump of the signal. I don't experience this when using blinker by itself. Is there a way to make it not output verbose statements to my console on a signal?

**Comment by jirikuncar** [comment]
You are probably using `app.debug = True`. Make sure you are using `datastore.commit()` instead of direct `db.session.commit()`.
