### ISSUE TITLE
Custom Datastores

### ISSUE THREAD

**Issue by kjaquier** [mattupstate/flask-security#493]
How would you create a custom [Datastore](https://pythonhosted.org/Flask-Security/api.html#datastores) to use another database or to add custom logic in user related operations?

I see two ways but both are problematic:

First solution: according to the documentation, it seems possible by overriding [`UserDatastore`](https://pythonhosted.org/Flask-Security/api.html#flask_security.datastore.UserDatastore). But it's not just an interface, it requires to pass an sqlalchemy/peewee-like model for user and role. Yet, in the implementation, these models are only used for the default implementation of [`UserDatastore`](https://github.com/mattupstate/flask-security/blob/develop/flask_security/datastore.py#L59), we don't need them if we're going to override all the methods.
I could pass `None` for `user_model` and `role_model`, but I would be relying on the implementation to not use them (which may change in a future version).

Second solution: I can just implement the [`DataStore`](https://github.com/mattupstate/flask-security/blob/develop/flask_security/datastore.py#L15) interface and use UserDatastore as a mixin, like [in the implementation](https://github.com/mattupstate/flask-security/blob/develop/flask_security/datastore.py#L178), but that's not documented (thus subject to change too). Plus, I'm still limited to orm-like models.

The issue here is that [`UserDatastore`](https://pythonhosted.org/Flask-Security/api.html#flask_security.datastore.UserDatastore) is part of the public API, but in order to use it, one must rely on hidden implementation details.

I would suggest to break UserDatastore into two classes: a base class that would provide no implementation and require no arguments (and be part of the public API), and the current class that extends it.

**Comment by jirikuncar** [comment]
The `UserDatastore` contains common code for all specialised data stores. If you are trying to implement datastore for a library that doesn't have API similar to SQLAlchemy or MongoDB then you will need to reimplement all methods.

**Comment by Seluj78** [comment]
The thing is, having to use a datastore or having to use MongoDB/SQLAlchemy limits us a lot.

For example, I am required to use PynamoDB right now and I can't use `Flask-Security` which is a real bummer... Any alternatives?
