### ISSUE TITLE
Request Signal UserLoggedIn and UserLoggedOut

### ISSUE THREAD

**Issue by erwinyusrizal** [mattupstate/flask-security#504]
Hi, Is there any signal that I can use after user loggedin and logged out? the purpose is in my case I want to create a statistic for example how many user logged in (online) 

Cheers,

**Comment by cstrutton** [comment]
if you look at the log in and out functions in utils.py you will find that the signal "identity_changed" is fired at both login (with user.id) and logout.

**Comment by cstrutton** [comment]
Still more rooting through the source code and I found _user_logged_in_ and _user_logged_out_ signals are fired (see [user_logged_in](https://github.com/maxcountryman/flask-login/blob/master/flask_login/utils.py#L178) and [user_logged_out](https://github.com/maxcountryman/flask-login/blob/master/flask_login/utils.py#L200)).

**Comment by erwinyusrizal** [comment]
aha yeah @cstrutton I got it now, it handled by flask-login not by flask-security, thanks!
