### ISSUE TITLE
Using subdomains

### ISSUE THREAD

**Issue by rcubarocha** [mattupstate/flask-security#521]
I am modifying an existing application for multi-tenancy through subdomains.

I see that one can set the Flask-Security's subdomain through `SECURITY_SUBDOMAIN` which I have set to `<subdomain>` to dynamically catch the name of the request's subdomain.

However, this now requires that the routes exposed by Flask-Security declare `subdomain` as one of their parameters, which they don't currently do.

As things are right now, the routes respond to being called from a subdomain, but end in errors like this:

`TypeError: logout() takes no arguments (1 given)`

The one argument given being the subdomain.

How can I have the routes handle the subdomain correctly?

**Comment by jonafato** [comment]
Can you provide a specific example of what isn't working? Flask-Security [passes the subdomain to the blueprint](https://github.com/mattupstate/flask-security/blob/9e5865d9735b0b292360f63588ed4725c376757e/flask_security/views.py#L327-L330), so each view function is not required to accept a `subdomain` argument individually.

**Comment by rcubarocha** [comment]
I'm not sure how much more specific I can get to be honest.

If I do not set the `SECURITY_SUBDOMAIN` config var, then the login-related routes work (i.e. login, logout, register...), but they only respond in the root domain (e.g. domain.com).

If I set `SECURITY_SUBDOMAIN`, then the same login-related respond at the subdomain (e.g. sub.domain.com), but stop working with the error I mentioned before where the route handler function gets passed an argument (the subdomain) that is not declared on its parameter list.

**Comment by cstrutton** [comment]
Did I not read somewhere that you can process a subdomain variable in a "before request" function.  Essentially strip out the subdomain variable and store it for later use?  Sorry I dont have time to elaborate more.

**Comment by jirikuncar** [comment]
@cstrutton yes, you can do it by registering blueprint with `..., subdomain="<subdomain>"`. Then  store it in `g.subdomain` in before request method and remove it from view arguments.
