### ISSUE TITLE
_render_json returning 200 in case of bad request/wrong password

### ISSUE THREAD

**Issue by shipperizer** [mattupstate/flask-security#525]
https://github.com/mattupstate/flask-security/blob/develop/flask_security/views.py#L52 

Here a `200 OK` status gets returned even in case of a failure, shouldn't it return the same code present in the `[meta][code]`?
PR here in case you think it's a good idea https://github.com/mattupstate/flask-security/pull/526

**Comment by jirikuncar** [comment]
closed via #526
