### ISSUE TITLE
Question: How to show /register view only to admin role?

### ISSUE THREAD

**Issue by bfrgoncalves** [mattupstate/flask-security#532]
Hi,

I was wondering if there is any option to filter the registration of users only for users with the admin role. Is there a way to apply the @roles_required decorator to the /register default route?

Thanks

**Comment by jirikuncar** [comment]
@bfrgoncalves please use `Flask-Admin` for exposing the database tables to admin users and disable `SECURITY_REGISTRABLE = False`.
