### ISSUE TITLE
Override flask_security: check email domain before register: is there a better way?

### ISSUE THREAD

**Issue by vision-mcgm** [mattupstate/flask-security#533]
Hello,

I'm using flask-security for logins and registrations. I'd like to add a feature: checking that a user has a .ac.uk domain name before registration. I also want to provide a password field on the register page: this password is required for registration.

As I understand it, I can't use a signal for this, becuse signals are async: the registration process will continue whatever happens after the signal is sent.

Am I right in thinking that the best way to do this is to override the register() function in flask_security.views?

Thanks
Fintan

**Comment by jonafato** [comment]
The easiest way to accomplish this would probably be to override the registration form ([docs](https://pythonhosted.org/Flask-Security/customizing.html#forms)) and use a [custom WTForms validator](https://wtforms.readthedocs.io/en/latest/validators.html#custom-validators) to check the email address for the domain.

**Comment by jonafato** [comment]
@vision-mcgm I'm going to close this issue. If you haven't found a solution that works for you yet, I'm happy to reopen / continue the discussion.

**Comment by vision-mcgm** [comment]
I managed this according to your advice - thank you for the advice!
Fintan
