### ISSUE TITLE
Password confirmation, SECURITY_CONFIRMABLE, RegisterForm, and ConfirmRegisterForm issue

### ISSUE THREAD

**Issue by movielady** [mattupstate/flask-security#54]
Stumbled over a problem this evening as I'm playing with flask-security. The docs say:

```
SECURITY_CONFIRMABLE
Specifies if users are required to confirm their email 
address when registering a new account. If this value
is True Flask-Security creates an endpoint to handle 
confirmations and requests to resend confirmation 
instructions. The URL for this endpoint is specified by 
the SECURITY_CONFIRM_URL configuration option.
Defaults to False.
```

Ok, no problem. 

I realized that the password confirmation field wasn't showing up on the register page, so I removed {% if register_user_form.password_confirm %} from around the password_confirm field rendering, and got this error: 

```
UndefinedError: 'flask_security.forms.ConfirmRegisterForm 
object' has no attribute 'password_confirm'
```

I tracked the problem down to line 103 in flask_security/views.py:

``` python
    if _security.confirmable or request.json:
        form_class = ConfirmRegisterForm
    else:
        form_class = RegisterForm
```

The only difference between ConfirmRegisterForm and RegisterForm is that RegisterForm calls the PasswordConfirmFormMixin. Neither form has anything, as far as I can tell, with sending confirmation emails. :) So, unless I'm completely missing something, I think the above bit from views.py should be changed to:

``` python
    if request.json:
        form_class = ConfirmRegisterForm
    else:
        form_class = RegisterForm
```

That's what I've done on my installation, at any rate (along with modifying the template as mentioned above), and it now correctly displays the password confirmation field. I haven't run into any issues yet, but I'm working on a local machine, not a live server, so I haven't tried sending associated emails yet. :)

**Comment by erwinyusrizal** [comment]
Hi Matt,

Regarding this issue, I think it's happen to me as well, when I set

`SECURITY_CONFIRMABLE = True`

and I have custom register template, it seems didnt load my model, for example I have extended registration form with field first_name, I got this error

`UndefinedError: 'flask_security.forms.ConfirmRegisterForm object' has no attribute 'first_name'`

I tried to change the view.py according to movielady said above

```
if request.json:
        form_class = ConfirmRegisterForm
    else:
        form_class = RegisterForm
```

it works, but cant register, it always thrown an error: Password doesnt match

Any Idea?

**Comment by erwinyusrizal** [comment]
Hi Matt,

Regarding this issue, I think it's happen to me as well, when I set

`SECURITY_CONFIRMABLE = True`

and I have custom register template, it seems didnt load my model, for example I have extended registration form with field first_name, I got this error

`UndefinedError: 'flask_security.forms.ConfirmRegisterForm object' has no attribute 'first_name'`

I tried to change the view.py according to movielady said above

```
if request.json:
        form_class = ConfirmRegisterForm
    else:
        form_class = RegisterForm
```

it works, but cant register, it always thrown an error: Password doesnt match

Any Idea?

**Comment by erwinyusrizal** [comment]
I understand now the flow for this, but still to make it work, I need to change the view.py according to **movielady** code

```
if request.json:
        form_class = ConfirmRegisterForm
    else:
        form_class = RegisterForm
```
