### ISSUE TITLE
post to login endpoint for token acquisition should respect USER_IDENTITY_ATTRIBUTES

### ISSUE THREAD

**Issue by dusktreader** [mattupstate/flask-security#540]
The addition of the SECURITY_USER_IDENTITY_ATTRIBUTES flag allows the application to use another field such as username as the identity attribute used to login. However, the security.login endpoint still expects there to be an 'email' field specified in the body of the post request. This should be fixed so that any field specified in the SECURITY_USER_IDENTITY_ATTRIBUTES configuration may be passed in the request.

**Comment by mafrosis** [comment]
duplicate of #482
