### ISSUE TITLE
make auth_required respect the LOGIN_DISABLED config flag

### ISSUE THREAD

**Issue by dusktreader** [mattupstate/flask-security#541]
It would be very nice to be able to use the LOGIN_DISABLED flag to disable authentication requirements for some unit tests.

The decorators 'auth_required' and 'auth_token_required' should respect the LOGIN_DISABLED flag.

**Comment by mafrosis** [comment]
Does the `LOGIN_DISABLED` config var even exist now? I can only see one reference to this in `tests/conftest.py`.

**Comment by jirikuncar** [comment]
@mafrosis `LOGIN_DISABLED` still exists. See https://github.com/maxcountryman/flask-login/blob/d769a321fbf3476c0d32baa6beb1aedcdc6fbf50/flask_login/login_manager.py#L119
