### ISSUE TITLE
Why is the UserDatastore using 'active' while in forms 'is_active' is used

### ISSUE THREAD

**Issue by sanderl-mediamonks** [mattupstate/flask-security#547]
Also in flask_login 'is_active' is used everywhere.

Does this mean we need both active and is_active on the User model?

**Comment by Eco-logical** [comment]
'is_active' is a Mixin lookup method. 
https://github.com/mattupstate/flask-security/blob/develop/flask_security/core.py#L309

**Comment by sanderl-mediamonks** [comment]
Ah, man.. Didn't see it. Thanks.
