### ISSUE TITLE
FlaskWTFDeprecationWarning

### ISSUE THREAD

**Issue by swedishmike** [mattupstate/flask-security#552]
I get the following error when running a Flask app at the moment:

<- Cut ->
sphuc.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = NameForm()
<- Cut ->

Having looked at the issue it seems that the warning is coming from/due to flask-security, more specifically this line in forms.py:

`from flask_wtf import Form as BaseForm`

If I understand things correctly that should instead read:

`from flask_wtf import FlaskForm as BaseForm`

**Comment by neaket360pi** [comment]
Looks like this was fixed in https://github.com/mattupstate/flask-security/pull/549

Can someone push up a new release to pypi?

**Comment by jirikuncar** [comment]
@neaket360pi if you need a quick solution, you can use Flask-Security-Fork from PyPI (`pip uninstall Flask-Security`, `pip install Flask-Security-Fork` - no other changes needed).

**Comment by neaket360pi** [comment]
Thanks @jirikuncar

**Comment by mixmastamyk** [comment]
How bout it?  Tired of warning messages taking up the console.

**Comment by jirikuncar** [comment]
closed via #553
