### ISSUE TITLE
Script fails on DeactivateUserCommand

### ISSUE THREAD

**Issue by Speedy1991** [mattupstate/flask-security#555]
`manager = Manager(app)
security = Security(app=app, user_datastore=user_datastore)
manager.add_command('deactivate_user', DeactivateUserCommand())`

calling it:
`python3 manage.py deactivate_user -u test@example.com`

leads to

```
 File "/usr/local/lib/python3.4/dist-packages/flask_security/datastore.py", line 136, in deactivate_user
    if user.active:
AttributeError: 'str' object has no attribute 'active'

```

ActivateUserCommand with same issue

get_user in datastore is **_never_** called, so the "NotImplemented" is never raised.
That was really confusing.

**Comment by jirikuncar** [comment]
There is a new CLI using Click implemented in https://github.com/inveniosoftware/flask-security-fork/pull/9. I hope you will find it useful. You can simply replace Flask-Security dependency with Flask-Security-Fork (note: the imports stay untouched).

**Comment by jirikuncar** [comment]
The CLI using Click has been integrated in #617.
