### ISSUE TITLE
Add token timeout after inactivity 

### ISSUE THREAD

**Issue by cydan33** [mattupstate/flask-security#560]
It would be a great feature if Flask-Security allowed to specify a specific time for token timeout after x minutes of inactivity (just like the SECURITY_TOKEN_MAX_AGE configuration)

**Comment by jirikuncar** [comment]
Please check following configuration options:
```python
{
    'LOGIN_WITHIN': '1 days',
    'CONFIRM_EMAIL_WITHIN': '5 days',
    'RESET_PASSWORD_WITHIN': '5 days',
}
```
