### ISSUE TITLE
Redirect Issue in @login_required decorator in flask_security

### ISSUE THREAD

**Issue by kartikdanidhariya** [mattupstate/flask-security#561]
hi i am using flask_security in my flask project 
i make successfully login using login_user(user) method 
i check it return true 
but after that it redirect to login page again
how can i solve this issue

**Comment by jonafato** [comment]
Please provide a minimal example (in code) demonstrating this issue.

**Comment by kartikdanidhariya** [comment]
hi my code is


from flask import Flask, render_template,request,url_for
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.security import Security, SQLAlchemyUserDatastore, \
    UserMixin, RoleMixin, login_required,login_user
from flask_mail import Mail, Message
from itsdangerous import (TimedJSONWebSignatureSerializer as Serializer, BadSignature, SignatureExpired)
from itsdangerous import URLSafeTimedSerializer
import datetime
from flask_security.utils import send_mail, md5, url_for_security, get_token_status, config_value, do_flash, get_message, send_mail, encrypt_password
from flask_security.signals import user_registered
from werkzeug.local import LocalProxy
_security = LocalProxy(lambda: app.extensions['security'])

_datastore = LocalProxy(lambda: _security.datastore)




# Create app
app = Flask(__name__)
app.config['DEBUG'] = True
app.config['SECRET_KEY'] = 'super-secret'
app.config['SECURITY_PASSWORD_SALT'] = "my_precious_two"
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///user.db'
app.config['SECURITY_RECOVERABLE'] = True
app.config['SECURITY_REGISTERABLE'] = True
app.config['SECURITY_CONFIRMABLE'] = True
app.config["SECURITY_LOGIN_WITHOUT_CONFIRMATION"] = True
#app.config["SECURITY_CONFIRM_URL"] = "/confirm_new"

app.config['WTF_CSRF_ENABLED'] = True
app.config['DEBUG_TB_ENABLED'] = False
app.config['DEBUG_TB_INTERCEPT_REDIRECTS'] = False

app.config['MAIL_SERVER']='mail.server.net'
app.config['MAIL_PORT'] = 465
app.config['MAIL_USERNAME'] = 'xxxxxxxxxxxxxxxxxxxx'
app.config['MAIL_PASSWORD'] = 'xxxxxxxxxxxxxxxxxxxx'
app.config['MAIL_USE_TLS'] = False
app.config['MAIL_USE_SSL'] = True
app.config['SEND_REGISTER_EMAIL'] = True
app.config['EMAIL_SUBJECT_REGISTER'] = 'aaaaaaaaaaaaaaaaa'
#app.config['SECURITY_SEND_REGISTER_EMAIL'] = True
mail = Mail(app)
# Create database connection object
db = SQLAlchemy(app)

# Define models
roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('role.id')))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())
    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))
   


# Setup Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)



@app.route("/RegisterUser" , methods = ['POST','GET']) 
def add_user():
    if request.method == "POST":   
        email = request.form['email']   
        pwd = request.form['pwd']
        #user_datastore.create_role(name='Admin')    
        user_datastore.create_user(email=email,password=pwd,active=False,roles=['Admin']) 
        db.session.commit()
     	confirmation_link, token = None, None
        user = User.query.filter_by(email=email).first()
        print "user",user

        confirmation_link, token = generate_confirmation_link(user)
        do_flash(*get_message('CONFIRM_REGISTRATION', email=email))


        send_mail(config_value('EMAIL_SUBJECT_REGISTER'), email, 'welcome',
                  user='kartik', confirmation_link=confirmation_link)
        user_login =login_user(user,remember=True)
        print "user_login",user_login

    return "User Registration Successfully..."
@app.route('/')
@login_required
def home():
    #return render_template('index.html')
    return "Login"





@app.route('/Login',methods=['GET','POST'])    
def LoginUser():    
    if request.method == "POST":
        print "----------------------------"
        print request.form   
        if User.query.filter_by(email=request.form['email']).first():
            usr = User.query.filter_by(email=request.form['email']).first()
            login_user(usr,remember=True)
            return "User Login Successfully..."  
    return "Not Login"      


def generate_confirmation_token(user):
    """Generates a unique confirmation token for the specified user.

    :param user: The user to work with
    """
    data = [str(user.id), md5(user.email)]
    return _security.confirm_serializer.dumps(data)

def generate_confirmation_link(user):
    token = generate_confirmation_token(user)
    return url_for_security('confirm_email', token=token, _external=True), token

def confirm_user(user):
    """Confirms the specified user

    :param user: The user to confirm
    """
	
    if user.confirmed_at is not None:
        return False
    user.confirmed_at = datetime.utcnow()
    user.active = True
    _datastore.put(user)
    user_confirmed.send(app._get_current_object(), user=user)
    return True



if __name__ == '__main__':
    app.run()

**Comment by jirikuncar** [comment]
@kartikdanidhariya I am not sure why do you reimplement the endpoints? If you don't want the default url handlers you can disable them by `security = Security(app, user_datastore, register_blueprint=False)`.

**Comment by bonsoirval** [comment]
I have the following code for my minimalist application.
#import Flask from flask
from flask import Flask
#pass current module (__name__) as argument
#this will initialize the instance

app = Flask(__name__)

#path to sqlite database
#this will create the db file in instance
#if database not present already
app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///g4g.sqlite3"
#needed for session cookies
app.config['SECRET_KEY'] = "07038616871"
#hashes the password and then stores in the database
app.config['SECURITY_PASSWORD_SALT'] = "kesandu loves you"
#allows new registrations to application
app.config['SECURITY_REGISTERABLE'] = True
#to send automatic registration email to user
app.config['SECURITY_SEND_REGISTER_EMAIL'] = False
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

#import SQLAlchemy for database operations
#and store the instance in 'db'
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate 

db = SQLAlchemy()
migrate = Migrate()
db.init_app(app)
migrate.init_app(app, db)

#runs the app instance
app.app_context().push()

#db models
#import UserMixin, RoleMixin
from flask_security import UserMixin, RoleMixin

#3 create table in database for assigning roles
roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('role.id')))

#create table in database for storing users
class User(db.Model, UserMixin):
    __tablename__='user'
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    email = db.Column(db.String, unique=True)
    password = db.Column(db.String(250), nullable=False, server_default='')
    active = db.Column(db.Boolean())

    #backreferences the user_id from roles_users table
    roles = db.relationship('Role', secondary=roles_users, backref = 'roled')

#createe table in database for storing roles
class Role(db.Model, RoleMixin):
    __tablename__='role'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)


#creates all database tables
@app.before_first_request
def create_tables():
    db.create_all()

#import required libraries from flask_login and flask_security
from flask_login import LoginManager, login_manager, login_user
from flask_security import Security, SQLAlchemySessionUserDatastore

#load users, roles for a session
user_datastore = SQLAlchemySessionUserDatastore(db.session, User, Role)
security = Security(app, user_datastore)

#immport the required libraries
from flask import render_template, redirect, url_for

#'/' URL is bound with index() function
@app.route('/')
#defining function index which returns the rendered thml code
#for our home  page
def index():
    return render_template('index.html')


#import 'request' to request data from html
from flask import request

#signup page 
@app.route('/signup', methods=['GET', 'POST'])
def signup():
    msg = ""
    #if the form is submitted
    if request.method == 'POST':
        #check if user already exists
        user = User.query.filter_by(email=request.form['email']).first()
        msg = ""
        #if user already exists render the msg
        if user:
            msg = "User already exists"
            #render signup.html if user exists
            return render_template('signup.html', msg=msg)
        #if user does not exist

        #store the user to database
        user = User(email=request.form['email'], active=1, password=request.form['password'])
        #store the role
        role = Role.query.filter_by(id=request.form['options']).first()
        user.roles.append(role)

        #commit the changes to database
        db.session.add(user)
        db.session.commit()

        #login the user to the app
        #this user s current user
        login_user(user)
        #redirect to index page
        return redirect(url_for('index'))

    #case other than submitting form, like loading the page itself
    else:
        return render_template('signup.html', msg=msg)

#signin page
@app.route('/signin',methods=['GET', 'POST'])
def signin():
    msg = ""
    if request.method == "POST":
        #search user in database
        user = User.query.filter_by(email=request.form['email']).first()
        #if exist check password
        if user:
            if user.password == request.form['password']:
                #if password matches, login the user
                login_user(user)
                return redirect(url_for('index'))
            #if password doesnt match 
            else:
                msg = "Wrong password"
        #if user does not exist
        else:
            msg = "User does not exist"
        return render_template('signin.html', msg=msg)
    
    else:
        return render_template('signin.html', msg=msg)

#to implement role based access
#import roles_accepted from flask_security 
from flask_security import roles_accepted, roles_required

#for teachers page
@app.route('/teachers')
#only admin can access the page
@roles_accepted('Admin')
def teachers():
    teachers = []
    #query for role teacher that is role_id = 2
    role_teachers = db.session.query(roles_users).filter_by(role_id=1)
    #query for the user's details using user_id
    for teacher in role_teachers:
        user = User.query.filter_by(id=teacher.user_id).first()
        teachers.append(user)
    #return the teachers list
    
    return render_template('teachers.html', teachers=teachers)

#for staff page
@app.route('/staff')
#only Admin and Teacher can access the page
@roles_accepted('Admin', 'Teacher')
def staff():
    staff = []
    role_staff = db.session.query(roles_users).filter_by(role_id=3)
    for staff in role_staff:
        user = User.query.filter_by(id=staff.user_id).first()
        staff.append(user)
    return render_template('staff.html', staff=staff)
                                                        
#for studend page
@app.route('/students')
#only 'Admin, Teacher and Staff can access the page'
@roles_accepted('Admin', 'Teacher','Staff')
def students():
    students = []
    role_students = db.session.query(roles_users).filter_by(role_id=4) 
    for student in role_students:
        user = User.query.filter_by(id=student.usesr_id).first()
        students.append(user)
    return render_template('students.html', students=students)

#for details page
@app.route('/mydetails')
#Admin, Teacher, Staff and Student can access the page 
@roles_accepted('Admin', 'Teacher', 'Staff', 'Student')
def mydetails():
    return render_template('mydetails.html')
    
#for running the app
if __name__ == "__main__":  
    app.run(debug = True)



I cannot access a view like this:
#for teachers page
@app.route('/teachers')
#only admin can access the page
@roles_accepted('Admin')
def teachers():
    teachers = []
    #query for role teacher that is role_id = 2
    role_teachers = db.session.query(roles_users).filter_by(role_id=1)
    #query for the user's details using user_id
    for teacher in role_teachers:
        user = User.query.filter_by(id=teacher.user_id).first()
        teachers.append(user)
    #return the teachers list
    
    return render_template('teachers.html', teachers=teachers)
even when using admin user. 
Please help and I appreciate any help.
