### ISSUE TITLE
Send confirmation mail on register user in flask_security

### ISSUE THREAD

**Issue by kartikdanidhariya** [mattupstate/flask-security#562]
hi,
i used flask_security in my flask project
when i register user it not send any confirmation mail to user
i want to send that mail whe n register is done and user can confirm registration from that link
how can i do that in flask-security.

**Comment by lohriialo** [comment]
You can try `app.config['MAIL_SUPPRESS_SEND'] = True`

Then follow the instructions here in docs https://pythonhosted.org/Flask-Security/quickstart.html#id4
