### ISSUE TITLE
How to merge login form and register form into the same form?

### ISSUE THREAD

**Issue by velerodro** [mattupstate/flask-security#563]
I want to have the login form and register form into one form. There is boolean "new_user", if it is True, I want it to register the new user, otherwise I want it to log the user in.

I have tried to do this by inheriting the existing forms instead of making a new one, but it does not work. What I have tried is the following:

```python
class FrontpageForm(LoginForm, RegisterForm):
  attribute = StringField('attribute , validators=[DataRequired()])
  new_user = BooleanField('new_user', default=True)

  def validate(self):
    if self.new_user.data:
      if not RegisterForm.validate(self):
        return False
    else:
      if not LoginForm.validate(self):
        return False
    return True
```

This code does not work (users are not logged in neither registered), but it does not raise any errors. I do not even know how to debbug this. Any help would be very much appreciated.

**Comment by melonista** [comment]
Just had to use ConfirmRegisterForm instead of RegisterForm.

**Comment by velerodro** [comment]
Just had to use ConfirmRegisterForm instead of RegisterForm.

**Comment by velerodro** [comment]
Reopening because when triying to register a user that already exists, raises a mysql exception

**Comment by jirikuncar** [comment]
@velerodro you will need to implement new url handler, or make redirection from login form when user doesn't exists (custom validator on `email` field).
