### ISSUE TITLE
TRACKABLE info is not stored when using login_user directly

### ISSUE THREAD

**Issue by avilaton** [mattupstate/flask-security#566]
We use
```
from flask_security import login_user
@app.route('/custom_login', methods=['POST'])
def custom_login():
    login_user(some_user)
    return redirect(...)
```
and noticed that information regarding current_login, last login, etc is not stored into the DB (sqlalchemy for us) unless we add a `db.session.commit()` after the `login_user(...)` call. 

After reading a bit the code, it looks like it could be fixed by adding a call to `after_this_request(db.session.commit)` in the `flask_securtity.utils.login_user` method. Not sure where we should add a unit test for this. Please if @mattupstate can hint us a bit on where is a good place to write the test for it, it would be great help to submit a PR and save you some work.

Thanks a lot.

**Comment by nfvs** [comment]
The documentation does mention that:
https://github.com/mattupstate/flask-security/blob/develop/flask_security/utils.py#L67

But it does make sense to do that automatically. Using `after_this_request(db.session.commit)` is the wrong approach though, since there's no guarantee that everyone uses a db. It's enough to call `_datastore.commit()` after the call to `_datastore.put(user)`.

**Comment by jirikuncar** [comment]
Since it's explicitly mentioned in documentation and adding explicit commit inside `login_user` would make it significantly harder to include the function inside a function with manually handled transaction, I am in favor of closing this issue.

**Comment by nfvs** [comment]
IMHO this behaviour is surprising, and will probably generate _more_ bug reports.

How about adding a parameter to `login_user()`, `db_commit=True`, which will decide if the session is committed or not? People can still pass `db_commit=False` if they want to manually do it themselves, but the default behavior (which I imagine will apply to the majority of people) will be to commit.

**Comment by jirikuncar** [comment]
I see you concern, however I am strongly against adding global side effect (=commit) to `login_user` function. I hope the documentation is sufficient for a person who would like to implement custom login behavior.

**Comment by nfvs** [comment]
Fair enough, but the side effect is already there, it's just pending :)
