### ISSUE TITLE
Kwargs not accepted at creation of Security object without both app and datastore

### ISSUE THREAD

**Issue by ianzimmerman** [mattupstate/flask-security#568]
Trying to create the security object at security.py like so:

    from flask_security import Security, SQLAlchemyUserDatastore
    from flask_security.forms import RegisterForm, ConfirmRegisterForm
    from .models import db, User, Role

    user_datastore = SQLAlchemyUserDatastore(db, User, Role)

    class ExtendedRegisterForm(RegisterForm):
        username = StringField(*ext_reg)

    ...

    security = Security(datastore=user_datastore, register_form=ExtendedRegisterForm)

Then in my create_app.py:
   
    app = Flask(__name__)
    from .security import security
    security.init_app(app)

The security instance does not get the extended reg form because it does not accept kwargs without the app AND the datastore

    class Security(object):
        """The :class:`Security` class initializes the Flask-Security extension.
        :param app: The application.
        :param datastore: An instance of a user datastore.
        """
        def __init__(self, app=None, datastore=None, **kwargs):
            self.app = app
            self.datastore = datastore

            if app is not None and datastore is not None:
                self._state = self.init_app(app, datastore, **kwargs)

        def init_app(self, app, datastore=None, register_blueprint=True,
                     login_form=None, confirm_register_form=None,
                     register_form=None, forgot_password_form=None,
                     reset_password_form=None, change_password_form=None,
                     send_confirmation_form=None, passwordless_login_form=None,
                     anonymous_user=None):

So then I have to import it to app factory and re-init the app with extended registration forms. 

    from ..security import security, user_datastore, 
        ExtendedConfirmRegisterForm, ExtendedRegisterForm
    security.init_app(app,
                      datastore=user_datastore,
                      register_form=ExtendedRegisterForm,
                      confirm_register_form=ExtendedConfirmRegisterForm
                      )

Is there a way to lazy load in the extended class forms?

**Comment by jirikuncar** [comment]
@ianzimmerman can you use app configuration instead? See new test case in https://github.com/inveniosoftware/flask-security-fork/pull/8.
