### ISSUE TITLE
user registration is trying to send confirmation email even though its disabled

### ISSUE THREAD

**Issue by clovehitch** [mattupstate/flask-security#569]
It looks like flask is trying to still send a confirmation email even though I have the option disabled. Is there something else that could be causing this? The user is still created but an error page is shown.

The setting I have configured:
app.config['SECURITY_REGISTERABLE'] = True
app.config['SECURITY_CONFIRMABLE'] = False

I have attached the error page.
[error.txt](https://github.com/mattupstate/flask-security/files/637586/error.txt)

**Comment by jirikuncar** [comment]
If you don't want any email to be send, please configure `SECURITY_SEND_REGISTER_EMAIL=False` [1].

--
[1] https://pythonhosted.org/Flask-Security/configuration.html#miscellaneous
