### ISSUE TITLE
Disable any API exposed by flask-security

### ISSUE THREAD

**Issue by yugi003** [mattupstate/flask-security#577]
I was trying to implement login functionality in my app. I started with using **flask-security** for basic api exposed by flask-security like register, login, logout etc.

While doing this, I realised that some of the API's provided by flask-security is not of my use. So for that, I was looking to disable some of the API but didn't get anything related to that.

I saw **flask-security-config**, but I didn't find any way to disable API which is exposed by flask-security.

I am new to flask & flask-security & struggled a lot but didn't get success. Any useful suggestion will be very helpful.

Thanks!

**Comment by jirikuncar** [comment]
@yugi003 have you tried to set different feature flags e.g. `SECURITY_REGISTERABLE`?

- docs: https://pythonhosted.org/Flask-Security/configuration.html#feature-flags
- code: https://github.com/mattupstate/flask-security/blob/develop/flask_security/views.py#L324-L371

**Comment by yugi03** [comment]
@jirikuncar : Sorry for replying too late. This doc: [ https://pythonhosted.org/Flask-Security/configuration.html#feature-flags](url) helped me to achieve what I wanted.
