### ISSUE TITLE
Upgrade PassLib for better hashes

### ISSUE THREAD

**Issue by BitLooter** [mattupstate/flask-security#578]
PassLib released 1.7.0 in November, bringing some new features - notably, support for argon2 and scrypt hashes. Argon2 especially, as it's a new algorithm built to be resistant to GPU-based attacks and was designed to replace bcrypt, scrypt, etc. Updating Flask-Security to use PassLib 1.7.0 would allow it to use these algorithms.

**Comment by jirikuncar** [comment]
PassLib version has been raised in 20de8297.
