### ISSUE TITLE
can't work with gunicorn with multiple works?

### ISSUE THREAD

**Issue by stamaimer** [mattupstate/flask-security#579]
I'm writing a website with Flask. I use `Flask-Secuirty` to do authentication. I use `nginx + gunicorn` to deploy it. And I use `gunicorn -w worker_number -k gevent run:app -p app.pid -b 127.0.0.1:5000` to start gunicorn. If the `worker_number` is `1`, everything is ok. If the `worker_number` is greater than `1` like `3`, I can't login in with `Flask-Security`. The output of server said the post request of login is 200. But the server redirect me to login page again.

**Comment by jirikuncar** [comment]
Can you provide full example app? Is it possible that you are using SQLite in-memory database?

**Comment by stamaimer** [comment]
Thanks for your reply.

I use MySQL database behind Flask-SQLAlchemy. The full example app host at https://github.com/stamaimer/MPWeChatRSS.

**Comment by jirikuncar** [comment]
@stamaimer I have test it with the example app with small modifications:

```
# ...

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'

# ...

# Create a user to test with
@app.before_first_request
def create_user():
    db.create_all()
    try:
        user_datastore.create_user(email='matt@nobien.net', password='password')
        db.session.commit()
    except Exception:
        db.session.rollback()
```

and it works fine using `gunicorn -w 5 -k gevent app:app -p app.pid -b 127.0.0.1:5000`.

```console
$ pip freeze
blinker==1.4
click==6.7
Flask==0.12
Flask-Login==0.3.2
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Security==1.7.5
Flask-SQLAlchemy==2.1
Flask-WTF==0.14.1
gevent==1.2.0
greenlet==0.4.11
gunicorn==19.6.0
itsdangerous==0.24
Jinja2==2.9.3
MarkupSafe==0.23
passlib==1.7.0
SQLAlchemy==1.1.4
Werkzeug==0.11.15
WTForms==2.1
```

**Comment by stamaimer** [comment]
can you login?

**Comment by stamaimer** [comment]
I also test with sqlite. But when i set the SERVER_NAME of flask, it's won't work. @jirikuncar

**Comment by jirikuncar** [comment]
When I change the homepage to
```python
# Views
@app.route('/')
@login_required
def home():
    return str(current_user.__dict__)
```
I can see `{'_sa_instance_state': , 'roles': [], 'confirmed_at': None, 'email': u'matt@nobien.net', 'active': True, 'password': u'password', 'id': 1}`.

**Comment by stamaimer** [comment]
After add --preload parameter to gunicorn, it works normally. But i still can't figure out the reason cause this problem.
