### ISSUE TITLE
Customizing register view switches which form class is used unexpectedly

### ISSUE THREAD

**Issue by UnicycleMatt** [mattupstate/flask-security#580]
1. I've created my own ExtendedRegisterForm class.

class ExtendedRegisterForm(RegisterForm):
	first_name = StringField('First Name', [validators.required()])
	last_name = StringField('Last Name', [validators.required()])
	phone_number = StringField('Phone Number', [validators.required()])

2. I am passing this into the Security object as such:

security = Security(app, user_datastore, register_form=ExtendedRegisterForm)

3. Concurrently, I have SECURITY_CONFIRMABLE set to True as I want to do email confirmation AND avoid having the password confirm field. I want to minimize unnecessary UI fields as you mention with this flag.

SECURITY_CONFIRMABLE = True

4. Finally, I've added new template variables to show my form inputs.

{{ render_field_with_errors(register_user_form.first_name, class_="form-control input-lg", placeholder="First Name") }}
{{ render_field_with_errors(register_user_form.last_name, class_="form-control input-lg", placeholder="Last Name") }}
{{ render_field_with_errors(register_user_form.phone_number, class_="form-control input-lg", placeholder="Phone Number") }}

5. However, now when I render my template, I get an exception stating that the ConfirmRegisterForm does not have any of these fields. It appears that Flask-Security is now choosing to render the ConfirmRegisterForm instead of the RegisterForm override. If I change my Security initializer, the form renders, but of course has the extra confirm password field.

security = Security(app, user_datastore, register_form=ExtendedRegisterForm, confirm_register_form=ExtendedRegisterForm)

The expected behavior would be to show the ExtendedRegisterForm in place of RegisterForm instead of ConfirmRegisterForm, and for the template to avoid having that password confirm field.

**Comment by biomap** [comment]
#601
