### ISSUE TITLE
send_reset_password_instructions() created invalid token when user ID is None

### ISSUE THREAD

**Issue by sybrenstuvel** [mattupstate/flask-security#582]
We've run into an issue where we have an admin interface to create new users. This interface has an `on_model_change(user)` callback, which is called when a new user is created. However, unbeknown to us, that user doesn't have a database ID set yet. As a result, we call `flask_security.recoverable.send_reset_password_instructions(user)` with`user.id = None`. When using this token to reset their password, the user causes the following exception:

```
2017-01-24 10:00:34,252     INFO werkzeug 127.0.0.1 - - [24/Jan/2017 10:00:34] "GET /reset/WyJOb25lIiwiZjdiMzhiZmJkZWU3Yjg1NDc5ZWFlNDEzMDkzZmM5YjYiXQ.C2ioAw.9HIuMSEvLDxTyu4Hutoc-gbd6ew HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/sybren/.virtualenvs/blender-id/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sybren/.virtualenvs/blender-id/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/sybren/.virtualenvs/blender-id/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sybren/.virtualenvs/blender-id/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sybren/.virtualenvs/blender-id/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sybren/.virtualenvs/blender-id/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sybren/.virtualenvs/blender-id/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sybren/.virtualenvs/blender-id/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sybren/.virtualenvs/blender-id/lib/python2.7/site-packages/flask_security/decorators.py", line 225, in wrapper
    return f(*args, **kwargs)
  File "/home/sybren/.virtualenvs/blender-id/lib/python2.7/site-packages/flask_security/views.py", line 269, in reset_password
    expired, invalid, user = reset_password_token_status(token)
  File "/home/sybren/.virtualenvs/blender-id/lib/python2.7/site-packages/flask_security/recoverable.py", line 73, in reset_password_token_status
    if user.password:
AttributeError: 'NoneType' object has no attribute 'password'
```
To me it seems like a bug that an unusable token is generated. It is especially nasty because the admin who creates the user doesn't see that there is anything wrong.

**Comment by sybrenstuvel** [comment]
PS: it might be seen as a different issue, but apparently `reset_password_token_status(token)` returns `invalid=False` even though `user=None`.

**Comment by jirikuncar** [comment]
@sybrenstuvel do you think you could provide a minimal example setup to reproduce it or a test case?

**Comment by biomap** [comment]
I ran into this when implementing private registration.  The current token method requires that token be assigned to a user so that it can look them up to gather the information it needs to send the request (ie email address).  I am not sure what you are doing however if you are not adding the user to the database but wanting to get the token status you will have to implement your own method of doing so.  If the user should be in the database and is not after you call on_model_change(user) (idk what that does) then make sure you are calling datastore.commit().

**Comment by sybrenstuvel** [comment]
Here is a minimal example that shows this issue:


```#!python
import flask_security.recoverable
import flask_security.datastore
import flask_mail
import flask

app = flask.Flask(__name__)
app.config['DEBUG'] = True
app.config['SECRET_KEY'] = 'super-secret'
app.config['SECURITY_RECOVERABLE'] = True

# Start an email server using "python3 -m smtpd -n -c DebuggingServer"
app.config['MAIL_PORT'] = 8025
app.config['DEFAULT_MAIL_SENDER'] = 'sender@example.com'


class User:
    def __init__(self, user_id):
        self.id = user_id
        self.password = 'secret'
        self.email = 'example@example.com'


class DummyDatastore(flask_security.datastore.Datastore):
    def put(self, model):
        pass

    def delete(self, model):
        pass

    def find_user(self, id):
        # This will show that it's called with id='None'
        raise ValueError('Invalid ID: %r' % id)


mail = flask_mail.Mail(app)
datastore = DummyDatastore(None)
security = flask_security.Security(app, datastore, register_blueprint=True)


@app.route('/')
def index():
    # This is obviously wrong. However, send_reset_password_instructions() doesn't
    # check its input, and happily encodes 'None' (as string) in the reset link.
    user = User(None)
    flask_security.recoverable.send_reset_password_instructions(user)
    return "Mail sent"


if __name__ == '__main__':
    app.run(debug=True)
```

To see the error, visit `http://127.0.0.1:5000/`, then visit the reset link that was mailed.

This is not so much a request to support users with `None` IDs, but a request to move the error message forward in the password reset flow. IMHO `send_reset_password_instructions(user)` should raise a `ValueError` when `user.id is None`. That way the error is seen earlier in the process, when the link gets generated, rather than when the link gets used. This is especially important due to the encoding of the reset token, which makes it impossible to visually observe that something is wrong with the link.

**Comment by biomap** [comment]
I see what you are saying now.

This is because you should not be able to create a token without being registered in the app as it stands.  All of the validation is done via the forms which IMO is the best way to do it.  It returns none from the DB so that it doesn't raise an error per se and kill the app.  Validation Errors are best handled via forms and not at the database level.  If this strategy is used then you will not have a None users.
