### ISSUE TITLE
peewee.OperationalError: Connection already open - on first run of example app

### ISSUE THREAD

**Issue by oz123** [mattupstate/flask-security#600]
Hi,
I ran the example as shown in the docs. Upon first run, I got the above exception.

Refreshing the page, makes this disappear. This scares me a be that if I use Peewee with flask I might
encounter more problems. Is there a chance someone looks into this?

### update 

if I call the function  directly I don't see this error, e.g.:
```
# @app.before_first_request
def create_user():
    for Model in (Role, User, UserRoles):
        Model.drop_table(fail_silently=True)
        Model.create_table(fail_silently=True)
    user_datastore.create_user(email='matt@nobien.net', password='password')

create_user()
```
Maybe it is an issue in flask_peewee?

**Comment by jirikuncar** [comment]
@oz123 the code is run only once when the application is started. It looks like you can't create tables when you already have an open session. In general is not good idea to create tables during request. Please consider creating command line interface for database manipulation instead.
