### ISSUE TITLE
SECURITY_CONFIRMABLE mixup between confirm password and confirm email

### ISSUE THREAD

**Issue by sdiepend** [mattupstate/flask-security#601]
I think there is some weird behaviour when using SECURITY_CONFIRMABLE.

The documentation states the following, so this is a flag to enable confirmation of an email address.

> SECURITY_CONFIRMABLE 	
> Specifies if users are required to confirm their email address when registering a new account. If this value is True, Flask-Security creates an endpoint to handle confirmations and requests to resend confirmation instructions. The URL for this endpoint is specified by the SECURITY_CONFIRM_URL configuration option. Defaults to False.

But when set to True it also removes the second password field, so I think this is mixing up email confirimation and password confirmation. 

register_user.html
```
{% if register_user_form.password_confirm %}
    {{ render_field_with_errors(register_user_form.password_confirm) }}
  {% endif %}
```

I think it has to do with the following two forms:
forms.py
```
class ConfirmRegisterForm(Form, RegisterFormMixin,
                          UniqueEmailFormMixin, NewPasswordFormMixin):
    pass


class RegisterForm(ConfirmRegisterForm, PasswordConfirmFormMixin,
                   NextFormMixin):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        if not self.next.data:
            self.next.data = request.args.get('next', '')
```

views.py
```
def register():
    """View function which handles a registration request."""

    if _security.confirmable or request.json:
        form_class = _security.confirm_register_form
    else:
        form_class = _security.register_form

```

**Comment by biomap** [comment]
Two completely different things register_user_form.password_confirm is a form validator.
https://github.com/mattupstate/flask-security/blob/develop/flask_security/forms.py#L125
security.confirmable (SECURITY_CONFIRMABLE=True) allows you to send confirmation emails before the user is activated.

**Comment by sdiepend** [comment]
Hello, why wontfix? I can have a go at it this weekend/next weekend if you want.

**Comment by sdiepend** [comment]
@jirikuncar I almost have a fix ready. But it doesn't give you the option to turn off retyping the password. (password confirmation).

**Comment by jirikuncar** [comment]
@sdiepend please check #580 since it looks very similar.

**Comment by sdiepend** [comment]
@jirikuncar I would add a SECURITY_RETYPABLE to add a flag to enable/disable the retyping of the password. But I'm not familiar with the testing setup, would you maybe have some time some day to walk me through?

**Comment by jirikuncar** [comment]
IMHO it should work by providing new form without password confirmation field. We should however document it.

```python
class RegisterForm(ConfirmRegisterForm, # without PasswordConfirmFormMixin,
                   NextFormMixin):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        if not self.next.data:
            self.next.data = request.args.get('next', '')
```
