### ISSUE TITLE
Anything more than getting started documentation?

### ISSUE THREAD

**Issue by JetForMe** [mattupstate/flask-security#602]
I've gone through the docs, and successfully integrated Flask-Security into my fledgling app, getting it to show a login form for the home page as described in the Getting Started section.

Now I'm looking to see how to do a number of additional things, and I can't find documentation describing how to use F-S to do these things (I did find lots of information on how to customize these, implying there's a default behavior available):

- Present a registration form
- Accept a registration form and create a new user record with a role (how do I define what roles get assigned)?
- Initiate forgot-password flow?
- Use a different auth mechanism (e.g. token-based)
- Initiate flow through any of the other forms implied by the section on templates.

**Comment by biomap** [comment]
Best bet is to search GH for others implementing Flask-Security.  The documentation however includes everything you are asking about.  This is all in [Configuration/feature flags](https://pythonhosted.org/Flask-Security/configuration.html#feature-flags]) .  The workflow is already built in and implemented you just turn on the feature set you wish to use (confirmable, registerable, recoverable etc).  The templates are built in you can copy them and to your template folder or configure to use other templates.  Token auth is there also.

**Comment by JetForMe** [comment]
I finally did figure it out, but it took a lot of googling. It took a while to figure out that I had to go to all the dependencies' docs to do things.

**Comment by biomap** [comment]
Word! sorry respond so late and to reopen but in reference to your comment...

This may help you or someone else that stumbles across this thread...

I have found it is super helpful to get the cmd line working and start inspecting the library (and flask object in general) especially if you have ipython running in your shell or better yet in an editor.  I prefer pycharm (free v avail) which will do just about everything you need all in one app including running shells , ssh, database (depending on if u pay) and deployment.  This will also allow you to browse your installed site-packages in a tree as well.  There is no better documentation than the package itself. :)

When you manage to get it running in a shell take a look at the `cls.__dict__` methods of the flask objects to see what all the configs and settings are of flask-security (FS) module and current_app (if you want to go crazy check out current_user too) as well as your current state and other important values.

example: `print current_app.extensions['security'].__dict__`  

I like flask-script and there are some scripts in the current [master](https://github.com/mattupstate/flask-security/blob/develop/flask_security/script.py) that are not used unless you build out a manage.py(or alike) with flask-script.  There is also another fork using the click library for newer (3/2017) flask installs.

FS wraps several diff libraries which are sort of abstracted from view (Flask-Login, Flask-Mail etc) so getting in and seeing what the config values are is helpful.

Also what makes this library great is that it is well written and thought out.   You have the ability to over class bits and pieces of it to make it do exactly what you would like it to do to with your custom workflow without much effort or rewriting.   For example if you would like to add to or change the methods of the user datastore that is very easy to do by inheritance.
example:
``` from flask-security import SQLAlchemyUserDatastore
class ModDatastore(SQLAlchemyUserDatastore):
    def my_special_method(self):
        ....stuff....
    def get_user(self, **kwargs):
        print "I'm over-writing the get_user method"


..... ur app init .....
sec = Security()
sec.init_app(app, datastore=ModDatastore(db, user, role))


```

If you decide to do something like this i suggest getting very familiar with super() and what it does.  Its a very powerful tool when over/super classing. You can even super  `security.core.Security` or even the entire `security.core` and gain control of parts or the entire module.

Happy hunting 👍
