### ISSUE TITLE
Some templates ignored

### ISSUE THREAD

**Issue by JetForMe** [mattupstate/flask-security#603]
It seems that flask-security ignores some templates, and not others. For example, I have a working `security/forgot_password.html`, but my `security/login_user.html` is completely ignored.

```
SECURITY_FORGOT_PASSWORD_TEMPLATE = security/forgot_password.html
SECURITY_LOGIN_USER_TEMPLATE = security/login_user.html
```

```
$ ls -R templates/
_macros.html	base.html	index.html	security/

templates//security:
change_password.html	forgot_password.html	login_user.html		reset_password.html
```

**Comment by JetForMe** [comment]
Update: it seems that if I rename my file to something else (e.g. `my_login_user.html`) and set `SECURITY_LOGIN_USER_TEMPLATE` to point to that, it picks it up.

**Comment by jirikuncar** [comment]
Can you verify that the `security` blueprint is correctly registered and you don't have any custom template loader?

**Comment by JetForMe** [comment]
Well, other templates do work. I don't know how to verify it's correctly registered, and I don't have a custom template loader unless some other component installed one.

**Comment by biomap** [comment]
When you overwrite a security template in myfabulousapp/templates/security you do not need to specify an alternative location for the template in configs.  FS will look in your templates/security/ folder first.  Try that and see if it picks it up.  Otherwise place it in another location templates/auth/myloginform.html and point to it there to see if it resolves.

**Comment by JetForMe** [comment]
My experience was this was not the case, unless I explicitly set the template path as described above.

**Comment by biomap** [comment]
From the Docs:
Overriding these templates is simple:

    Create a folder named security within your application’s templates folder
    Create a template with the same name for the template you wish to override

You can also specify custom template file paths in the configuration.

**Comment by JetForMe** [comment]
That's exactly what I have, and it didn't see my templates without me also setting `SECURITY_LOGIN_USER_TEMPLATE`.

**Comment by biomap** [comment]
hmm.. i can confirm this totally works.  I use it on several apps.  I would double check your code to see if you have something wonky going on which interferes with this.  Like I said move it and test it to see if it picks it up. Try without the config and test.  As I said in the other post, times like this is where having access to the shell is nice.

**Comment by jirikuncar** [comment]
I can confirm that it works for me and I can't reproduce this issue with latest `develop` branch.
