### ISSUE TITLE
AttributeError: 'AnonymousUserMixin' object has no attribute 'roles'

### ISSUE THREAD

**Issue by threemonks** [mattupstate/flask-security#607]
When I logout, I got this error:

AttributeError: 'AnonymousUserMixin' object has no attribute 'roles'

Debugging shows that it comes from core.py:_on_identity_loaded() line 218:
```
    for role in current_user.roles:
        identity.provides.add(RoleNeed(role.name))
```

Right after logout, current_user is a AnonymousUserMixin from flask_login.mixins, which does not have such attribute roles.

Can you add a check if current_user have attribute 'roles' before you loop through it?

**Comment by jirikuncar** [comment]
@threemonks the anonymous user class should be `flask_security.core:AnonymousUser`.
