### ISSUE TITLE
How to disable all routes and views

### ISSUE THREAD

**Issue by r0b1n1sl4m** [mattupstate/flask-security#609]
I've been building a REST API & using flask-security to manage user accounts. I'm using it's inner functions but I don't need any routes and views as I've developed something custom with it. So for some reason I need to disable the routes and views so that nobody can access anything like /login,/confirm etc. Is there any option available? If yes please help me with that.

**Comment by biomap** [comment]
register_blueprint = False
https://github.com/mattupstate/flask-security/blob/develop/flask_security/core.py#L413

**Comment by r0b1n1sl4m** [comment]
Thank you very much, This is exactly what I was looking for :)
