### ISSUE TITLE
Can't custom login_form when create the instance of Security

### ISSUE THREAD

**Issue by stamaimer** [mattupstate/flask-security#618]
I use the factory pattern of Flask. I create Security instance with `security = Security(datastore=user_datastore, login_form=AppLoginForm)`, and then init it with `security.init_app(app)`. But the login_form still the default of Flask-Security. It works use follows code`security = Security(datastore=user_datastore)` and `security.init_app(app, login_form=AppLoginForm`. I want to use a consistent method to init all my extension in a for loop. But if i can't assign the custom login form of Flask-Security, It might break that consistent.

**Comment by jirikuncar** [comment]
You can set the login form in config value `SECURITY_LOGIN_FORM`.

--
see also https://github.com/inveniosoftware/flask-security-fork/blob/master/tests/test_misc.py#L256-L276

**Comment by stamaimer** [comment]
@jirikuncar I can't find the configuration key named `SECURITY_LOGIN_FORM` in document or the source of Flask-security.

**Comment by stamaimer** [comment]
I have try it. It worked. Thanks.
