### ISSUE TITLE
Wrong I18N_DOMAIN or po-files names

### ISSUE THREAD

**Issue by yoursdearboy** [mattupstate/flask-security#622]
Greetings. I can't get translations work with default value of `I18N_DOMAIN='flask_security'`. It seems to be incorrect because translations po-file has name `messages.po`. As I understand from [Flask-BabelEx documentation](http://pythonhosted.org/Flask-BabelEx/#flask.ext.babelex.Domain) then filename should be `flask_security.po`:

> class flask.ext.babelex.Domain(dirname=None, domain='messages')
> Localization domain. By default will use look for tranlations in Flask application directory and “messages” domain - all message catalogs should be called messages.mo.

I've installed flask-security with pip using git://..@develop and then compiled messages manually with `pybabel compile -d translations`. Have I missed some keys?

Also, it would be nice to have an option to override domain to use custom translations from applications directory (or maybe just set a constant with path), then `I18N_DOMAIN` definitely should be `flask_security`.

**Comment by jirikuncar** [comment]
@yoursdearboy you are right. There was missing configuration in `setup.cfg`. Please check #623.

**Comment by yoursdearboy** [comment]
@jirikuncar thx you for fast response, works now.

One more question on this - is it possible to integrate `pybabel compile` into `setup.py` somehow? It's a bit strange to do it manually for 3rd party module.

**Comment by jirikuncar** [comment]
@yoursdearboy `python setup.py compile_catalog` should work.
