### ISSUE TITLE
Putting .mo files into repository

### ISSUE THREAD

**Issue by themylogin** [mattupstate/flask-security#627]
As I've understood, Flask-Admin is [considered](https://github.com/mattupstate/flask-security/issues/626) to be an example of well-done internationalized Flask extension. They [put](https://github.com/flask-admin/flask-admin/tree/master/flask_admin/translations/de/LC_MESSAGES) compiled .mo files along with .po files into repository (and thus, PyPi distribution), because it is really [inconvenient](https://github.com/mattupstate/flask-security/issues/622) to run `python setup.py compile_catalog` manually (e.g. how do I run it when installing Flask-Security from requirements.txt with CI?). Maybe, Flask-Security should also do so?

**Comment by jirikuncar** [comment]
@themylogin the `.mo` files will be included in the released package (see https://github.com/mattupstate/flask-security/blob/develop/.travis.yml#L62). I would not recommend to depend on Git repo in production environment.
