### ISSUE TITLE
Add support for Argon2

### ISSUE THREAD

**Issue by inkadnb** [mattupstate/flask-security#630]
Since Passlib has been updated, would like to see support for Argon2. I assume this simply needs to be added to the PASSWORD_SCHEMES list in core.py?

**Comment by jirikuncar** [comment]
@inkadnb you are right. You can simply add `argon2` to `SECURITY_ PASSWORD_SCHEMES` configuration. There is no need of changing `core.py` at the moment.

**Comment by mrx23dot** [comment]
Please reopen, it gives me error saying I need to choose from the listed items when setting argon2 to SECURITY_ PASSWORD_SCHEMES, needs adding to core.py
