### ISSUE TITLE
Reset password functionality doesn't work

### ISSUE THREAD

**Issue by agua19940824** [mattupstate/flask-security#640]
I have same problem.
Flask-Security ==1.7.5
Flask-SQLAlchemy==2.2
SQLAlchemy==1.1.9
```
main.py
from flask_sqlalchemy import SQLAlchemy
from flask_security import current_user, login_required, RoleMixin, Security, \
	SQLAlchemyUserDatastore, UserMixin, utils
app = Flask(__name__)
app.config.from_object('config')
db = SQLAlchemy(app)
```
```
config.py

#SQLALCHEMY_COMMIT_ON_TEARDOWN = True
```
When I didn't  set SQLALCHEMY_COMMIT_ON_TEARDOWN = True,  after submit the reset_password_form, it appears **sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <User at 0x6d415c0> is not bound to a Session; lazy load operation of attribute 'roles' cannot proceed** and the new password didn't put into the database.

When I set SQLALCHEMY_COMMIT_ON_TEARDOWN = True, click RecoverPassword button , it appears **sqlalchemy.orm.exc.DetachedInstanceError: Instance <User at 0x6af0320> is not bound to a Session; attribute refresh operation cannot proceed**, but i can through the email link change my password..

**Comment by jirikuncar** [comment]
@agua19940824 can you please check if you can reproduce the problem with latest `develop` branch?

**Comment by jirikuncar** [comment]
@agua19940824 please note that we are committing after request, hence `SQLALCHEMY_COMMIT_ON_TEARDOWN` is not necessary. Please re-open the issue if you are still experiencing the problem on latest branch and include the output of `pip freeze` command. Thank you!
