### ISSUE TITLE
Missing Flask-Peewee dependency

### ISSUE THREAD

**Issue by yoursdearboy** [mattupstate/flask-security#643]
Hi. I have a problem with `develop` version. Probably it's because of missing Flask-Pewee dependency in setup.py's `install_requires`?

> Traceback (most recent call last):
>   File "/Users/kirill.voronin/Work/apps_ng_2/hsctbio/hsctbio.py", line 15, in <module>
>     from flask_security import SQLAlchemyUserDatastore, Security
>   File "/Users/kirill.voronin/.virtualenvs/hsctbio/lib/python3.5/site-packages/flask_security/__init__.py", line 14, in <module>
>     from .datastore import SQLAlchemyUserDatastore, MongoEngineUserDatastore, \
>   File "/Users/kirill.voronin/.virtualenvs/hsctbio/lib/python3.5/site-packages/flask_security/datastore.py", line 12, in <module>
>     from peewee import fn as peeweeFn
> ImportError: No module named 'peewee'

**Comment by jonafato** [comment]
The Flask-Peewee dependency is declared [here](https://github.com/mattupstate/flask-security/blob/7abf19d0d0a436301654320f3dad197925c7c6ec/setup.py#L12). I'm unable to reproduce this. Does reinstalling Flask-Security in a new virtualenv fix the issue?

**Comment by yoursdearboy** [comment]
No, it doesn't.
Here is `pip freeze` output I've got in clean virtualenv:
```
appdirs==1.4.3
Babel==2.4.0
blinker==1.4
click==6.7
Flask==0.12.2
Flask-BabelEx==0.9.3
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Security==2.0.1
Flask-WTF==0.14.2
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
packaging==16.8
passlib==1.7.1
pyparsing==2.2.0
pytz==2017.2
six==1.10.0
speaklater==1.3
Werkzeug==0.12.2
WTForms==2.1
```
It's the same whether I use pip + git or clone and install from directory or using `python setup.py install`.
I don't think `tests_require`s would be installed since they are required only for development.

**Comment by jrast** [comment]
As Flask Security works with different Flask database extensions, you must install the correct extension by yourself, this is at least how I understand the concept.

Normally, if your app needs Flask-Pewee, this extension is in your requirements anyway.

**Comment by jirikuncar** [comment]
We can separate the test dependencies to optional extra requirements, however I agree with @jrast  that if your app needs Flask-Pewee, you should have it installed anyway.

**Comment by yoursdearboy** [comment]
Actually my app doesn't require neither `Flask-Pewee`, nor `pewee`. I agree that it would be nice to install manually only necessary ORM modules.

But in [\_\_init\_\_.py on line 15](https://github.com/mattupstate/flask-security/blob/develop/flask_security/__init__.py#L15) Flask-Security imports all datastores from [datastore.py which imports both - pewee and sqlalchemy](https://github.com/mattupstate/flask-security/blob/develop/flask_security/datastore.py#L12). That's what causing the problem.

If Flask-Security shouldn't depend on ORM modules, I suppose it should be somehow in try-catch block.

**Comment by yoursdearboy** [comment]
Try this [Dockerfile](https://gist.github.com/yoursdearboy/e5365d1e90dbdf069cc2441cd9101d09) please.

**Comment by jirikuncar** [comment]
@yoursdearboy this is of course a bug which I missed.
