### ISSUE TITLE
Storing LB ip in current_login_ip and last_login_ip

### ISSUE THREAD

**Issue by kvnaveen7** [mattupstate/flask-security#645]
Hi, When tracking is enabled flask security is storing Load Balancer ip i.e remote_addr is storing not x-forwarded-for.

**Comment by jirikuncar** [comment]
@kvnaveen7  are you using [`ProxyFix`](http://werkzeug.pocoo.org/docs/0.12/contrib/fixers/#werkzeug.contrib.fixers.ProxyFix) in your app?
