### ISSUE TITLE
signal for login/logout

### ISSUE THREAD

**Issue by RedCraig** [mattupstate/flask-security#648]
Hey there,

Is there a way to execute my own code after a login or logout of a user?

Right now I'm using all flask-security defaults, so logins/outs go straight through flask-security methods.
There don't appear to be any signals for login/outs.

Thanks for any help,
Craig

**Comment by RedCraig** [comment]
Ah, I was looking specifically at the flask-security signals list. 
flask-login has login/out signals:
https://flask-login.readthedocs.io/en/latest/#signals
I assume they'll do the trick.

**Comment by jirikuncar** [comment]
Exactly!
