### ISSUE TITLE
encrypt_password requires app context

### ISSUE THREAD

**Issue by mixmastamyk** [mattupstate/flask-security#652]
Hi, have a model, with a password field to encrypt:

```
class User(BaseModel, UserMixin):
    def __init__(self, name='', email='', password=None, ...)
        self.password = encrypt_password(password)
```
But this raises: `RuntimeError: Working outside of application context.`

Seems like password hashing should not be tied to the flask app?

**Comment by mixmastamyk** [comment]
I found a better example, though it still seems hashing should be available outside the app context.

https://github.com/sasaporta/flask-security-admin-example/blob/master/main.py

**Comment by jirikuncar** [comment]
@mixmastamyk the password encryption requires app context because it depends on configuration options.
