### ISSUE TITLE
CircleCI: invalid input syntax for integer: "untrackable"

### ISSUE THREAD

**Issue by RedCraig** [mattupstate/flask-security#658]
When running on CircleCI I'm getting:
```
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.DataError) invalid input syntax for integer: "untrackable"
LINE 1: ...-06-13T18:27:27.207671'::timestamp, last_login_ip='untrackab...
```
I have:
`SECURITY_TRACKABLE = True`
and
my `Users` model is:
```python

class Users(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())
    last_login_at = db.Column(db.DateTime())
    current_login_at = db.Column(db.DateTime())
    last_login_ip = db.Column(db.Integer)
    current_login_ip = db.Column(db.Integer)
    login_count = db.Column(db.Integer)

    roles = db.relationship('Role',
                            secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))
```
the `last_login_ip` is an int, which obviously won't work with a string `'untrackable'` value.

What am I doing wrong here? Should I change the table model, or is there some way to change the default untrackable value?
Thanks.

**Comment by jonafato** [comment]
This behavior was changed in #449.

**Comment by RedCraig** [comment]
Perhaps I should be using a string type rather than an int for `last_login_ip`?
I can't quite remember where I got the `db.Integer` from. It's not specified in the models: https://pythonhosted.org/Flask-Security/models.html#trackable
or in the [sqlalchemy-quickstart](https://pythonhosted.org/Flask-Security/quickstart.html#sqlalchemy-application).

**Comment by jirikuncar** [comment]
@RedCraig the `'untrackable'` string should be changed to `None/NULL`.
