### ISSUE TITLE
security issue concerning username/password combination

### ISSUE THREAD

**Issue by wisepotato** [mattupstate/flask-security#659]
Now this seems like a glaring security issue. When I input a wrong password but a correct username it gives back : this password is incorrect. SHouldn't it return:
```
Username/password combination is incorrect
```
Instead of  allowing me to guess a username first?

**Comment by jonafato** [comment]
This is a duplicate of #476. This should be fixed, but the message can be overridden as a stopgap solution. If you can, please submit a pull request with this change.

**Comment by wisepotato** [comment]
sure, let me cook something up
