### ISSUE TITLE
Email confirmation behavior

### ISSUE THREAD

**Issue by kesara** [mattupstate/flask-security#662]
At the moment confirmation token can be logs user in automatically.
I suggest this behavior should be, so this can be configured as required.

Other issue with the current confirmation tokens is they can be reused to login without using password as long as that token is not expired.

**Comment by jirikuncar** [comment]
@kesara thank you for reporting. We should make sure that any of the tokens (confirm, reset) is not reusable. The confirmation should fail if the user has been already confirmed.

The problematic parts with automatic login are:
- https://github.com/mattupstate/flask-security/blob/develop/flask_security/views.py#L232-L234
- https://github.com/mattupstate/flask-security/blob/develop/flask_security/views.py#L294

Do you have a proposal for the configuration option `SECURITY_...LOGIN...`?

My observation is that we should not execute `login_user(user)` and logout only if the `user != current_user`.

```python
    if current_user.is_authenticated and user != current_user:
        logout_user()
```

WDYT?

**Comment by kesara** [comment]
@jirikuncar I agree, it's better to logout if the `user != current_user`.
But I think it's better to make `login_user(user)` on unconfirmed accounts configurable with a configuration option like `SECURITY_CONFIRMABLE_AUTO_LOG`.
So for those who using that feature can keep using it with setting that option.

**Comment by jirikuncar** [comment]
@kesara I am just trying to understand the possible situations in combination with `_security.login_without_confirmation`. IMHO we should ask user at least once for the password after registration if the confirmation is required, but it should be probably configurable as you proposed. The option should be same also for the `reset_password` use-case.

WDYT about following option `SECURITY_AUTO_LOGIN_AFTER_TOKEN = {'confirm', 'reset'}`?

**Comment by kesara** [comment]
Did you meant to say `SECURITY_AUTO_LOGIN_AFTER_TOKEN = {'confirm', 'login'}` because user is supposed to enter a new password when they register? But `{'confirm', 'login'}` could be confusing.

Isn't `login_without_confirmation` only allow unconfirmed users to login? In that case I don't see this code change affecting that functionality.

I agree that it's better to ask for the password after confirmation, I only suggested that because that change could break the existing functionality. May be the for clarity and security better off removing `login_user(user)` from `confirm_email(token)`?

**Comment by jirikuncar** [comment]
I would say that we remove the automatic login even if it less convenient for users.

` SECURITY_AUTO_LOGIN_AFTER_TOKEN = {'confirm', 'reset'}` - I really meant `reset` and not `login` (see https://github.com/mattupstate/flask-security/blob/develop/flask_security/views.py#L294)

**Comment by jwag956** [comment]
Question - this is a (albeit small) behavior/backward incompatible change. As such is this appropriate for a minor release? or should this be reserved for a major release (and if we want it is a minor release - then add a default=false config option? (and change the default to true in the next major release)?
