### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by patrickyan** [mattupstate/flask-security#666]
https://pythonhosted.org/Flask-Security/ still thinks the latest is 1.7.5

**Comment by jirikuncar** [comment]
Pythonhosted is deprecated. Please use http://flask-security.readthedocs.io/en/latest/

**Comment by patrickyan** [comment]
That's even older. It think the latest is 1.7.4...

**Comment by snachx** [comment]
+1
Latest version on pythonhosted is 1.7.5
Latest version on readthedocs is 1.7.4

**Comment by jirikuncar** [comment]
@patrickyan @snachx I see that there were some issues with building the latest docs on Read the Docs. I have manually updated the pythonhosted.org, however please note that once we fix the Read the Docs, the https://pythonhosted.org/Flask-Security/ site might disappear.
