### ISSUE TITLE
Error when request is JSON but a list rather than an object

### ISSUE THREAD

**Issue by rossgray** [mattupstate/flask-security#681]
Hi,

We are hitting an issue when upgrading to version 3.0.0 with the following line of code:
https://github.com/mattupstate/flask-security/blob/develop/flask_security/core.py#L231

Our application responds to JSON-RPC requests and it is perfectly acceptable to send batch requests, in which case the JSON request is actually an array of requests. This means `request.get_json()` returns a list rather than a dict, and so `data.get(args_key, token)` fails with `'list' object has no attribute 'get'`.

As a side note - from what I can see, it is not possible to bypass Flask-Security for certain requests (even if the view doesn't require auth, it still goes through the Flask-Security middleware to identify the user, etc). In our case we would like to use Flask-Security for our admin views but we use our own authentication for our API views. Is there any way we can bypass the middleware for our API views? If not, having some mechanism like what Flask-Principal does for static files would be useful: https://github.com/mattupstate/flask-principal/blob/0b5cd06b464ae8b60939857784bda86c03dda1eb/flask_principal.py#L471-L473

Thanks

**Comment by Morabaraba** [comment]
I hacked it with.

```sh
~# diff old/flask_security/core.py new/flask_security/core.py 
231,232d230
<         if isinstance(data, list):
<             data = {}
```

Wanted to create a issue last week but life.

How did you fix it?

**Comment by Morabaraba** [comment]
Hi @rossgray 

Regarding your side note. You can change the `login_manager.request_loader` as seen below.

```py
	# Setup Flask-Security
	user_datastore = SQLAlchemySessionUserDatastore(db.session, User, Role)
	security = Security(app, user_datastore,
		login_form=ExtendedLoginForm)
	
	from flask_security.core import _request_loader 
	def my_request_loader(request):
		app.logger.debug('my_request_loader')
		if request.is_json:
			return security.login_manager.anonymous_user()
		else:
			return _request_loader(request) # call the default flask_security loader
			
	app.login_manager.request_loader(my_request_loader)
```

Hope it helps,

**Comment by rossgray** [comment]
Thank you @Morabaraba, that is very helpful. I will wait for the fix to be released before upgrading to version 3.x

**Comment by abhimskywalker** [comment]
Thank you @Morabaraba ! 👍 
A slightly modified version of the mentioned snippet helped:
```python
from flask_login import AnonymousUserMixin
# .
# .
# .
        # Setup Flask-Security
	user_datastore = SQLAlchemySessionUserDatastore(db.session, User, Role)
	security = Security(app, user_datastore,
		login_form=ExtendedLoginForm)
	
	from flask_security.core import _request_loader 
	def my_request_loader(request):
		my_app.logger.debug('my_request_loader')
		if request.is_json:
			return AnonymousUserMixin()
		else:
			return _request_loader(request) # call the default flask_security loader
			
	my_app.login_manager.request_loader(my_request_loader)
```
Just using `security.login_manager.anonymous_user()` threw my app into an infinite loop with`RecursionError` :/

**Comment by eipiminus1** [comment]
This just bit me. Is there a roadmap on when the fix might be released?

**Comment by jirikuncar** [comment]
@eipiminus1 check #788
