### ISSUE TITLE
email sender

### ISSUE THREAD

**Issue by williamcheng-web** [mattupstate/flask-security#685]
if set `MAIL_DEFAULT_SENDER` not set `SECURITY_EMAIL_SENDER`, email can't be sent.
In utils.py `send_mail` function:

    msg = Message(subject,
                  sender=_security.email_sender, 
                  recipients=[recipient])`,  
`sender` is a `LocalProxy` instance. So, `mail.send(msg)`  will happen `ValueError: too many values to unpack`. Because in flask-mail `sanitize_address` function:

    def sanitize_address(addr, encoding='utf-8'):
        if isinstance(addr, string_types):
            addr = parseaddr(force_text(addr))
        nm, addr = addr

`addr` is a `LocalProxy` instance. `isinstance(addr, string_types)` is `False`. So, `nm, addr = addr` goes wrong, `ValueError: too many values to unpack`.

**Comment by johncarmack1984** [comment]
I'm in the same place you were when you wrote  this. Any ideas on a fix?

**Comment by Chamaeleon-** [comment]
A quick and short fix:
https://github.com/mattupstate/flask-security/pull/695

**Comment by Tumetsu** [comment]
Having the same problem. Would be nice to get this merged.

**Comment by kuba-lilz** [comment]
Any roadmap for when master with fix to this problem will be release on pip?
Currently I have to manually install flask security with `pip install git+https://github.com/mattupstate/flask-security`, which doesn't get traced in Conda's environment definition.
