### ISSUE TITLE
Cannot send registration email

### ISSUE THREAD

**Issue by ochronus** [mattupstate/flask-security#693]
When I configure the app to send registration emails, registration fails with:

ValueError: too many values to unpack

See https://github.com/mattupstate/flask-mail/issues/148

I traced back the error to this line:
https://github.com/mattupstate/flask-security/blob/develop/flask_security/utils.py#L387
the _security var is a LocalProxy

cc @filipmihal

**Comment by jirikuncar** [comment]
@ochronus we should probably change it to `str(_security.email_sender)`.

**Comment by fernandocamargoai** [comment]
@jirikuncar when will be the next release with this issue fixed? And is there any workaround?

**Comment by leonprou** [comment]
I think this is solved my issue. Too bad it's not in master branch, do you have a plans to release a new tag soon? Now I use a develop version of the branch and not so happy about it.

**Comment by jirikuncar** [comment]
I will try to add one in January.
