### ISSUE TITLE
Different registration and login forms for different roles

### ISSUE THREAD

**Issue by velerodro** [mattupstate/flask-security#720]
Hello,

I'd like to make different forms for different roles. They share the basic fields, but then each role must have extra fields. Also they have different behaviour, for example one of the roles require manual activation by us.

I know I could import the forms, then extend them, and then create custom views/routes for this forms. In these views I can use e.g. `from flask_security.registerable import register_user` to register the users. Is there any issue with doing it like that? Is there a better way?

Thanks!

**Comment by jirikuncar** [comment]
@velerodro it is perfectly fine to create new routes for custom registration.

**Comment by jirikuncar** [comment]
Please re-open if you need this feature or you are willing to write a tutorial for other users. Thanks!
