### ISSUE TITLE
Flask-Security doesn't set cookie security flags by default

### ISSUE THREAD

**Issue by Avamander** [mattupstate/flask-security#742]
It would be really nice if Flask-Security nicely set Secure, HttpOnly and [SameSite](https://github.com/pallets/flask/issues/2030)(not fully supported yet) flags to it's cookies by default. 

The flags can be indeed enabled manually by specifying but I think especially a security package should be secure by-default.
```
    SESSION_COOKIE_SECURE = True
    REMEMBER_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    REMEMBER_COOKIE_HTTPONLY = True
```

**Comment by italomaia** [comment]
Aren't these Flask specific configuration? It would probably be a good thing, security wise, to set them to True by default, but that could impact usability for newcomers (Flask wise). In the flask-security side of the force, what if a warning message was shown if these options are set to False? Something like:
"Hey pal, set SOMETHING settings to True for better security" 

Not required, but a link explaining why setting it to true is a good thing would also be nice.

**Comment by Avamander** [comment]
Warnings about setting to false (or not setting to true) would indeed be a good idea, mention in the documentation definitely doesn't hurt either.

**Comment by illume** [comment]
SESSION_COOKIE_SAMESITE is now available in git flask. See https://github.com/pallets/flask/pull/2607/files However, flask hasn't had a release for about 8 months.

Warnings would be good... but also... Throw an error if they are false?

**Comment by jirikuncar** [comment]
There has been many improvement in Flask. Please follow http://flask.pocoo.org/docs/1.0/security/

**Comment by illume** [comment]
It's not clear to me that the requested secure settings are enabled, or warnings given for the flask-security routes. I think this should be reopened.

**Comment by jirikuncar** [comment]
@illume feel free to submit a PR with the docs improvements or optional warnings. I am not sure if it is a good strategy to change Flask defaults by installing an extension (even when it's called "security").
