### ISSUE TITLE
The hash_password function takes None as the password parameter

### ISSUE THREAD

**Issue by Kurandur** [mattupstate/flask-security#746]
Is it intended that the function `verify_password` takes None as an password argument? 

```
>>> from flask_security.utils import hash_password
>>> password_hash = hash_password(None)
>>> password_hash
'$2b$12$TKE9Eg3IO4d0zHEz2RvE8eTA6TrYFQcJXRfTDHAnTnwXQZ5LHl2Ii'
>>> verify_password(None, password_hash)
True 
```

**Comment by jirikuncar** [comment]
Does it cause any problems? The user should not be able to set it to `None` if the form validation works well.

**Comment by Kurandur** [comment]
I was just used to this behaviour from other libraries and a testcase failed. But you are right and an empty password shouldnt reach the function anyway-
