### ISSUE TITLE
After how long is the password reset token expired?

### ISSUE THREAD

**Issue by sdiepend** [mattupstate/flask-security#752]
Where can I find after how long the token in the password reset url expires?
Can I set it to expire after x time somewhere?

**Comment by biomap** [comment]
https://pythonhosted.org/Flask-Security/configuration.html

config value:   SECURITY_RESET_PASSWORD_WITHIN
default: 5 days

**Comment by sdiepend** [comment]
@biomap Thanks, didn't see that. But where is it used/loaded? 
https://github.com/mattupstate/flask-security/search?utf8=%E2%9C%93&q=SECURITY_RESET_PASSWORD_WITHIN&type=
Only shows results in the docs.

**Comment by biomap** [comment]
the within config values are truncated but I believe its implemented here: https://github.com/mattupstate/flask-security/blob/develop/flask_security/recoverable.py#L74

**Comment by biomap** [comment]
Yes when it checks the token status (all of them) then it hits get_max_age() https://github.com/mattupstate/flask-security/blob/develop/flask_security/utils.py#L418 and adds the _WITHIN tag to the end.  https://github.com/mattupstate/flask-security/blob/develop/flask_security/utils.py#L349

**Comment by sdiepend** [comment]
Ok, I think I understand now and the SECURITY_ part is stripped too. I must say it wasn't easy for me.

```python

    try:
        data = serializer.loads(token, max_age=max_age)
    except SignatureExpired:
        d, data = serializer.loads_unsafe(token)
        expired = True
    except (BadSignature, TypeError, ValueError):
        invalid = True
```

Where serializer is an instance of URLSafeTimedSerializer which is imported from itsdangerous.

```python
def _get_serializer(app, name):
    secret_key = app.config.get('SECRET_KEY')
    salt = app.config.get('SECURITY_%s_SALT' % name.upper())
return URLSafeTimedSerializer(secret_key=secret_key, salt=salt)
```

**Comment by biomap** [comment]
Correct.  Idk why it strips it for some of the config lookups but not with others.  We could use a refactor of lots of the code base to make it more uniform.  There are lots and lots of small things like this throughout that look like they got shoved in over time esp in utilities, forms and views. Lower case vs uppercase, shortened vs not, stripped prefix vs. not stripped.  I have gone through most of it with a fine tooth comb when I was doing my mod and finally gave up on the after a while as I ended up nearly rewriting the entire thing. LOL

**Comment by biomap** [comment]
On a side note that config value (token max age) could also be added to the form validators so that when you get an age error for your token it tells you more information about how old or what the max age is.  I think I added this into mine.

**Comment by jirikuncar** [comment]
The up-to-date link to the docs is http://flask-security.readthedocs.io/en/latest/configuration.html#miscellaneous (or [search](http://flask-security.readthedocs.io/en/latest/search.html?q=SECURITY_RESET_PASSWORD_WITHIN)).
