### ISSUE TITLE
Typo in documentation > Quick Start > Proxy Configuration

### ISSUE THREAD

**Issue by gouyou** [mattupstate/flask-security#757]
In the documentation for Quick Start > [Proxy Configuration](https://pythonhosted.org/Flask-Security/quickstart.html#id8), the line:
``` python
from werkzeug.config.fixers import ProxyFix
```
Should be:
``` python
from werkzeug.contrib.fixers import ProxyFix
```

**Comment by jirikuncar** [comment]
closed via d764909b

**Comment by buchbend** [comment]
Just wanted to let you know that the typo is still online at https://pythonhosted.org/Flask-Security/quickstart.html#id8 which is what brought me here...

**Comment by biomap** [comment]
I fixed it but it was posted to the develop branch.  I'm sure the website is pulling from the master so idk what happened.
