### ISSUE TITLE
RuntimeError: The configuration value `SECURITY_PASSWORD_SALT` must not be None when the value of `SECURITY_PASSWORD_HASH` is set to "bcrypt"

### ISSUE THREAD

**Issue by eliaperantoni** [mattupstate/flask-security#759]
I've tried running the example script at https://pythonhosted.org/Flask-Security/quickstart.html#id1 but when I open the url I get this error

```
RuntimeError: The configuration value `SECURITY_PASSWORD_SALT` must not be None when the value of `SECURITY_PASSWORD_HASH` is set to "bcrypt"
```

What am I doing wrong?
Is settings the security password hash config to `bcrypt.gensalt()` on startup a good idea?

**Comment by biomap** [comment]
You need to set SECURITY_PASSWORD_SALT in your configuration settings as it indicates in the traceback.

**Comment by iPadGuy** [comment]
SUGGESTION: Add the SECURITY_PASSWORD_SALT to the QuickStart.  I can't recomend this software if the QuickStart doesn't even work.

Thanks!

**Comment by jwag956** [comment]
@iPadGuy FYI - in my maintained fork - it is there in addition to actually showing how to generate a good SALT and SECRET_KEY.

https://flask-security-too.readthedocs.io/en/stable/quickstart.html
