### ISSUE TITLE
Recover Password button does nothing

### ISSUE THREAD

**Issue by chriscate** [mattupstate/flask-security#761]
I have made a few changes to allow users to log in with a username rather than an email address. That all works fine. I'm now setting up password reset functionality, and when I click the button to recover the password using the default template, nothing happens other than I see a POST request to the reset URL (the page I am already on) with a 200 response.  I don't get redirected anywhere and no email gets sent.  I have configured mail.

Here are the changes I made to forms.py:
```
class ExtendedLoginForm(LoginForm):
    email = StringField('Username', [Required()])

class ExtendedForgotPasswordForm(ForgotPasswordForm):
    username = StringField('Username')
```

and this change to config.py
`SECURITY_USER_IDENTITY_ATTRIBUTES = 'username'`

I also set the following in config.py
```
SECURITY_RECOVERABLE = True
SECURITY_SEND_PASSWORD_RESET_EMAIL = True
```

Any thoughts on what might be going on here?

Thanks

EDIT: fixed typo pointed out by @scraggelz

**Comment by scraggelz** [comment]
Not sure if you made a typo but try:
`SECURITY_SEND_PASSWORD_RESET_EMAIL`

instead of 
`SEND_PASSWORD_RESET_EMAIL`

**Comment by chriscate** [comment]
@scraggelz thanks.  Oddly enough I had left `SECURITY` off (whoops!), but even after correcting that, still nothing.  Any direction as to what _should_ get called on the click of this button? That may help narrow it down too...

**Comment by scraggelz** [comment]
I'm not sure exactly what's being called. I imagine it'd be trying to send an email to the email that a user signed up with. I'm not sure the difference between `SECURITY_SEND_PASSWORD_RESET_EMAIL` and `SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL` but it might be worth it to give it a shot. 

https://pythonhosted.org/Flask-Security/configuration.html#miscellaneous

**Comment by biomap** [comment]
Notice is after it's reset ie.  "Your password has been reset at hostname if this is incorrect please notify an administrator."

**Comment by biomap** [comment]
when you are customizing your forms make sure you are following this paradigm https://pythonhosted.org/Flask-Security/customizing.html

**Comment by chriscate** [comment]
@biomap thanks - I did follow that paradigm so in my mind it should be working.

I must be missing something. If there's any info that would help uncover what's going on let me know.  In the meantime I'll triple check what I've done.  Thanks for the replies so far.

**Comment by chriscate** [comment]
I should note that it's not that it does absolutely nothing when I click the button after entering a username.  Checking the browser console, it seems to generate a csrf token, but the screen doesn't change and no email is sent.

**Comment by biomap** [comment]
So a couple of things to note.  Without more information on what you have done or your configuration I'm afraid there is not much else I or anyone can do besides take shots in the dark.  I would consider suggesting turning on debug and using a console that you can see exactly what is happening.

Secondly,  if you are logged in while you are trying this it will not work.  You can reset your password while you are logged in however trying to recover your password while you are logged in will not work and cancels out like you are indicating.   It assumes you already know it because you are logged in.

**Comment by chriscate** [comment]
EDIT: deleting and closing this issue.  I think it's caused because I use a username to login instead of an email.  It doesn't even seem to do any validation when I override the forgot_password_form and replace email with username.  I can put in any text I want.  If I leave it as email, it will tell me that the user doesn't exist, etc. (of course they all don't exist, because we use username not email).  I've dug down to this https://github.com/mattupstate/flask-security/blob/3e15d06ee82a728d5cc53059fb28406c7bc6e7aa/flask_security/forms.py#L103-L107 but I'm still struggling to understand how user is set .

Anyway, if I find anything that I think will be applicable and helpful to others, I'll post it here.

Thanks again for the replies.
