### ISSUE TITLE
PynamoDB Datastore

### ISSUE THREAD

**Issue by Seluj78** [mattupstate/flask-security#774]
Hi there ! I've been trying to do a PynamoDB User Datastore based on the MongoDB one and I'm stuck.
Here's my `datastore.py` :  https://codeshare.io/5zvqBr

I've copied over parts of Flask-Security's datastore.py and renamed some to match pynamodb's name.
Yet i'm stuck on how to retreive users and access them. Any idea ?

**Comment by Seluj78** [comment]
I've opened an issue @PynamoDB to see if they'd know how to do it: https://github.com/pynamodb/PynamoDB/issues/495

**Comment by zprobst** [comment]
I've managed to implement it with a Global Secondary Index. You have to create a Global Secondary Index with email as a Hash Key. Flask security can come to your datastore and ask for the user with either an id or an email so you need to support both. A Global Secondary Index is the way to do so. 

A few notes:

You can read about setting a global secondary index [here](https://pynamodb.readthedocs.io/en/latest/indexes.html#global-secondary-indexes). 

Also, the above code does not do error handling. PynamoDB is going to throw an exception if a record with that key does not exist in the table. Same thing for the GSI. 

```
from flask_security.datastore import Datastore, UserDatastore


class DynamoDatastore(Datastore):
    def put(self, model):
        model.save()
        return model

    def delete(self, model):
        model.delete()


class DynamoUserDatastore(DynamoDatastore, UserDatastore):
    def __init__(self, user_model, role_model):
        UserDatastore.__init__(self, user_model, role_model)

    def get_user(self, identifier):
        print(identifier)
        return self.user_model.email_index.query(identifier).next()

    def find_user(self, **kwargs):
        user_id = kwargs.get('id', None)
        email = kwargs.get("email", None)
        if user_id is not None:
            return self.user_model.get(user_id)
        elif email is not None:
            return self.user_model.email_index.query(email).next()
        else:
            return None
```

**Comment by zprobst** [comment]
The more I think about it, you could lie a little bit to flask security and have the two fields have the same value and then you wouldn't need a secondary index. However, the rest of my application somewhat depends on having an arbitrary id. Also, this means changing a person's email would be tricky to implement and could really break things. Something else to explore.
