### ISSUE TITLE
Redirect unauthorized user to specific url

### ISSUE THREAD

**Issue by Usman17** [mattupstate/flask-security#775]
I want to redirect user to specific url if user tries open a restricted page without login.
i.e
```
@roles_accepted('admin')
def dashboard():
 //code
```
And in config.py i have added this line
SECURITY_UNAUTHORIZED_VIEW = '/login'
to redirect user to login page but it always redirect user to home page('/').

**Comment by IronFist16** [comment]
Check my question & answer on S.O. [here](https://stackoverflow.com/questions/49965994/login-required-decorator-not-redirecting-to-correct-endpoint/49967672#49967672).

**Comment by JonesH** [comment]
As far as I can see, `roles_accepted` can still take a few kwargs...
