### ISSUE TITLE
Release a minor version to PyPi

### ISSUE THREAD

**Issue by landmaj** [mattupstate/flask-security#799]
There has been no release since June 2017. A minor version release with fixes would be appreciated. 

For example this fix (https://github.com/mattupstate/flask-security/commit/a6479bebc26fbe07496c02c8abf76aff64f23949) is almost a year old, yet the release version still tries to call .get() on strings (which are just as valid JSON as objects or arrays). This breaks my test cases and forces me to write nasty hacks to fix it in my code.

**Comment by lnielsen** [comment]
@mattupstate A new release would be much appreciated. Similar we're dependent on fixes done in the past year.

**Comment by chrisroat** [comment]
@jirikuncar
