### ISSUE TITLE
Argon2 Compatibility

### ISSUE THREAD

**Issue by amahlaka** [mattupstate/flask-security#818]
I have been trying to implement Flask-Security to my project, which is currently using Argon2 for password hashing, Does Flask-Security have any sort of Argon2 Support built in or is any planned?

**Comment by bmjjr** [comment]
Its been a while, but I overrode the flask_security/utils.py  `hash_password` method to make it work. It's entirely possible there is an easier way to do it than what is shown here.  

    def hash_password(password):
    """Hash the specified plaintext password.

    It uses the configured hashing options.

    .. versionadded:: 2.0.2

    :param password: The plaintext password to hash
    """
    if use_double_hash():
        password = get_hmac(password).decode('ascii')

    # this is the part that was overriden to allow changing defaults for
    # argon2 like {'argon2__default_rounds': 5}
    # https://passlib.readthedocs.io/en/stable/narr/context-tutorial.html#context-tutorial
    return _pwd_context.using(**config_value('PASSWORD_HASH_OPTIONS',
                                             default={})).hash(password, _security.password_hash)

Then, in a settings.py file, something like:

    SECURITY_PASSWORD_HASH = 'argon2' #  'bcrypt' is default
    # this modifies the CryptContext
    SECURITY_PASSWORD_HASH_OPTIONS = {'argon2__rounds': 3,
                                      'argon2__parallelism': 2,
                                      'argon2__memory_cost': 61440,
                                      'argon2__salt_size': 16,
                                      'argon2__hash_len': 16}
    SECURITY_HASHING_SCHEMES = [
        'sha256_crypt',
        'hex_md5'] # it is a list
    SECURITY_PASSWORD_SCHEMES = [
        'argon2',
        'bcrypt',
        'des_crypt','pbkdf2_sha256',
        'pbkdf2_sha512','sha256_crypt','sha512_crypt',
        # And always last one...
        'plaintext']
