### ISSUE TITLE
How to disable default registration page and only allow a custom page?

### ISSUE THREAD

**Issue by amahlaka** [mattupstate/flask-security#826]
On my code, there are 2 different registration pages with different url's, i want to only use those pages for registration, not the default '/register' page. The custom pages have their own view functions

**Comment by alaa-aqeel** [comment]
To create a custom page, update the configuration
**view_template** : `SECURITY_REGISTER_USER_TEMPLATE `
**url** :  `SECURITY_REGISTER_URL` 
**But this is for just one page**

[ **Docs Configuration**](https://flask-security.readthedocs.io/en/3.0.0/configuration.html)
