### ISSUE TITLE
Maintainers - Who?

### ISSUE THREAD

**Issue by italomaia** [mattupstate/flask-security#854]
Hello. Currently, who are the official maintainers for this extension? I ask because, if memory serves me right, some time ago there was this discussion about who was maintaining the project and new maintainers stepped up. 
Is that still the case? Are new maintainers needed? Is someone looking into the PRs? Some are really old.

**Comment by italomaia-bk** [comment]
@avilaton @jirikuncar @mklassen

**Comment by acidjunk** [comment]
FWIW: There is a fork that has a lot of the PR's applied.
https://pypi.org/project/Flask-Security-Too/

**Comment by illume** [comment]
The github page for the fork is here: https://github.com/jwag956/flask-security

**Comment by derek-adair** [comment]
No releases since 2017.... oof.

**Comment by louking** [comment]
see the maintained clone: flask-security-too
https://pypi.org/project/Flask-Security-Too/
