### ISSUE TITLE
custom templates/security/reset_password.html doesn't get rendered

### ISSUE THREAD

**Issue by davidthewatson** [mattupstate/flask-security#99]
I have a flask app using flask security with the following templates:

templates/security
├── login_user.html
├── register_user.html
├── reset_password.html
└── send_confirmation.html

Login, register, and confirm all work as advertised. That is, my custom version of the forms gets rendered when I request /login, /register, and /confirm. However, when I request /reset, I get the default reset_password.html template from flask security. I've examined the flask security code and I don't see anything obviously wrong and since there is no code invoked in my application outside of the template, I'm not sure how to debug this.

Any ideas?

My reset_password.html is as follows:

```
{% from 'security/_macros.html' import render_field, render_field_with_errors %}
{% extends 'base.html' %}
{% block body_class %}main main-register{% endblock %}
{% block content %}
<div class="page-header">
  <h1>Reset Password</h1>
</div>
{% if login_failed %}
<h3>Register with your {{ provider.name }} account: {{     connection_values['display_name'] }}</h3>
{% endif %}
<div class="row content">
  <div class="span4 offset1">
{% include "security/_messages.html" %}
<form action="{{ url_for_security('reset_password', token=reset_password_token) }}" method="POST" name="reset_password_form">
    {{ reset_password_form.hidden_tag() }}
    {{ render_field_with_errors(reset_password_form.password) }}
    {{ render_field_with_errors(reset_password_form.password_confirm) }}
    {{ render_field(reset_password_form.submit) }}
</form>
</div>
</div>
{% endblock %}
```

Thanks!

**Comment by reustle** [comment]
I feel silly, but I just ran into this same issue for the 3rd time in the past few years. The link to this page was still purple, too 😄  I'm thinking I'm not the only one.

Now that I see this again, it makes sense, but maybe some slight alterations can be made to the docs? I'm not able to think of what could be changed, but maybe someone else has a good suggestion. Just basically to highlight that forgot_password and reset_password are separate pages (which is logical), and to be sure you're setting the proper template file.
